Repository stellar/go, pull requests merged in 2018-02, with the labels that each got.

#196 Adds Stellar.StartingBalance config field
  services/bifrost/README.md
  services/bifrost/bifrost.cfg
  services/bifrost/config/main.go
  services/bifrost/main.go
  services/bifrost/stellar/account_configurator.go
  services/bifrost/stellar/main.go
  services/bifrost/stellar/transactions.go
Labels: bifrost, in progress

#312 typo
  services/federation/README.md
Labels: in progress

#307 horizon trades and trade aggregations changelog
  services/horizon/CHANGELOG.md
Labels: in progress

#295 Link to Stack Exchange
  services/horizon/internal/docs/reference/admin.md
Labels: in progress

#315 Fix slow effects page query
  services/horizon/internal/db2/history/effect.go
Labels: horizon, in progress

#323 Update admin.md
  services/horizon/internal/docs/reference/admin.md
Labels: in progress

#310 Fix links in doc
  services/horizon/internal/docs/reference/resources/account.md
Labels: in progress

#328 update travis snapshots deployment to use go 1.9
  .travis.yml
Labels: in progress

#332 Fix panic triggered in `GetAsset`
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
Labels: in progress

#331 Update horizon binary links to v0.12.0-testing
  services/horizon/README.md
Labels: in progress

#327 tools/stellar-archivist: support custom S3 endpoints
  tools/stellar-archivist/README.md
  tools/stellar-archivist/internal/archive.go
  tools/stellar-archivist/internal/archive_test.go
  tools/stellar-archivist/internal/fs_archive.go
  tools/stellar-archivist/internal/http_archive.go
  tools/stellar-archivist/internal/mock_archive.go
  tools/stellar-archivist/internal/s3_archive.go
  tools/stellar-archivist/main.go
Labels: in progress
