Repository stellar/go, pull requests merged in 2018-04, with the labels that each got.

#394 better rebase - fixed test scenario script
  services/horizon/db.go
  services/horizon/internal/ingest/system.go
  services/horizon/internal/scripts/build_test_scenarios.bash
Labels: in progress

#393 Add fields to payment endpoint
  clients/horizon/responses.go
Labels: in progress

#395 Misc Fixes w/ Removal of `support/http/server` package
  .gitignore
  clients/stellarcore/client.go
  clients/stellarcore/client_test.go
  protocols/stellarcore/info_response.go
  protocols/stellarcore/info_response_test.go
  protocols/stellarcore/tx_response.go
  services/bifrost/server/server.go
  services/compliance/main.go
  services/federation/main.go
  services/friendbot/init_friendbot.go
  services/friendbot/internal/friendbot_test.go
  services/friendbot/main.go
  services/horizon/internal/txsub/submitter.go
  services/horizon/main.go
  support/config/main.go
  support/http/logging_middleware.go
  support/http/logging_middleware_test.go
  support/http/mux.go
  support/http/server/chi-router.go
  support/http/server/config.go
  support/http/server/factory.go
  support/http/server/middleware_logger.go
  support/log/main.go
  support/log/main_test.go
  support/render/problem/main.go
Labels: in progress

#397 update xdr definitions
  Gemfile.lock
  Rakefile
  meta/bundle.go
  services/horizon/internal/codes/main.go
  xdr/Stellar-ledger-entries.x
  xdr/Stellar-ledger.x
  xdr/Stellar-overlay.x
  xdr/Stellar-transaction.x
  xdr/Stellar-types.x
  xdr/signer_key.go
  xdr/xdr_generated.go
Labels: in progress

#399 Fix trade tests
  services/horizon/internal/db2/history/trade.go
  services/horizon/internal/db2/history/trade_test.go
  services/horizon/internal/test/scenarios/account_merge-core.sql
  services/horizon/internal/test/scenarios/account_merge-horizon.sql
  services/horizon/internal/test/scenarios/allow_trust-core.sql
  services/horizon/internal/test/scenarios/allow_trust-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_account-core.sql
  services/horizon/internal/test/scenarios/asset_stat_account-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_operations-core.sql
  services/horizon/internal/test/scenarios/asset_stat_operations-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_1-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_1-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_2-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_2-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_3-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_3-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_4-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_4-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_5-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_5-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_6-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_6-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_7-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_7-horizon.sql
  services/horizon/internal/test/scenarios/base-core.sql
  services/horizon/internal/test/scenarios/base-horizon.sql
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/change_trust-core.sql
  services/horizon/internal/test/scenarios/change_trust-horizon.sql
  services/horizon/internal/test/scenarios/ingest_asset_stats-core.sql
  services/horizon/internal/test/scenarios/ingest_asset_stats-horizon.sql
  services/horizon/internal/test/scenarios/kahuna-core.sql
  services/horizon/internal/test/scenarios/kahuna-horizon.sql
  services/horizon/internal/test/scenarios/non_native_payment-core.sql
  services/horizon/internal/test/scenarios/non_native_payment-horizon.sql
  services/horizon/internal/test/scenarios/order_books-core.sql
  services/horizon/internal/test/scenarios/order_books-horizon.sql
  services/horizon/internal/test/scenarios/order_books_310-core.sql
  services/horizon/internal/test/scenarios/order_books_310-horizon.sql
  services/horizon/internal/test/scenarios/pathed_payment-core.sql
  services/horizon/internal/test/scenarios/pathed_payment-horizon.sql
  services/horizon/internal/test/scenarios/paths-core.sql
  services/horizon/internal/test/scenarios/paths-horizon.sql
  services/horizon/internal/test/scenarios/self_send-core.sql
  services/horizon/internal/test/scenarios/self_send-horizon.sql
  services/horizon/internal/test/scenarios/send_to_issuer-core.sql
  services/horizon/internal/test/scenarios/send_to_issuer-horizon.sql
  services/horizon/internal/test/scenarios/set_options-core.sql
  services/horizon/internal/test/scenarios/set_options-horizon.sql
  services/horizon/internal/test/scenarios/trades-core.sql
  services/horizon/internal/test/scenarios/trades-horizon.sql
Labels: in progress

#404 docs: fix typo in TradeAggregation documentation
  services/horizon/internal/resource/main.go
Labels: in progress

#401 Add trade_aggregations endpoint in Go client
  clients/horizon/client.go
  clients/horizon/main.go
  clients/horizon/mocks.go
  clients/horizon/responses.go
Labels: client, horizon, in progress

#403 Add information about migrations to Bifrost README
  services/bifrost/README.md
Labels: bifrost, in progress

#405 Add HTTP 400 message in case of negative cursors
  services/horizon/internal/actions/base.go
  services/horizon/internal/actions/helpers.go
Labels: horizon, in progress

#411 [Documentation] Update horizon guide, use 'go get' instead of 'git clone'
  services/horizon/internal/docs/reference/admin.md
Labels: horizon, in progress, sdk

#313 Bifrost 0.0.2
  build/main.go
  build/transaction.go
  clients/horizon/main.go
  clients/horizon/mocks.go
  services/bifrost/README.md
  services/bifrost/bifrost.cfg
  services/bifrost/config/main.go
  services/bifrost/database/main.go
  services/bifrost/database/postgres.go
  services/bifrost/database/schema.go
  services/bifrost/images/accounts.png
  services/bifrost/main.go
  services/bifrost/server/main.go
  services/bifrost/server/server.go
  services/bifrost/server/stellar_events.go
  services/bifrost/sse/main.go
  services/bifrost/stellar/account_configurator.go
  services/bifrost/stellar/main.go
  services/bifrost/stellar/transactions.go
  support/config/main.go
Labels: bifrost, in progress

#417 restore trades for account endpoint
  services/horizon/internal/actions_trade.go
  services/horizon/internal/actions_trade_test.go
  services/horizon/internal/db2/history/trade.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/latest.sql
  services/horizon/internal/db2/schema/migrations/11_add_trades_account_index.sql
  services/horizon/internal/init_web.go
  services/horizon/internal/main_generated.go
  services/horizon/internal/test/scenarios/account_merge-core.sql
  services/horizon/internal/test/scenarios/account_merge-horizon.sql
  services/horizon/internal/test/scenarios/allow_trust-core.sql
  services/horizon/internal/test/scenarios/allow_trust-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_account-core.sql
  services/horizon/internal/test/scenarios/asset_stat_account-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_operations-core.sql
  services/horizon/internal/test/scenarios/asset_stat_operations-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_1-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_1-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_2-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_2-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_3-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_3-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_4-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_4-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_5-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_5-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_6-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_6-horizon.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_7-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_7-horizon.sql
  services/horizon/internal/test/scenarios/base-core.sql
  services/horizon/internal/test/scenarios/base-horizon.sql
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/blank-horizon.sql
  services/horizon/internal/test/scenarios/change_trust-core.sql
  services/horizon/internal/test/scenarios/change_trust-horizon.sql
  services/horizon/internal/test/scenarios/ingest_asset_stats-core.sql
  services/horizon/internal/test/scenarios/ingest_asset_stats-horizon.sql
  services/horizon/internal/test/scenarios/kahuna-core.sql
  services/horizon/internal/test/scenarios/kahuna-horizon.sql
  services/horizon/internal/test/scenarios/non_native_payment-core.sql
  services/horizon/internal/test/scenarios/non_native_payment-horizon.sql
  services/horizon/internal/test/scenarios/order_books-core.sql
  services/horizon/internal/test/scenarios/order_books-horizon.sql
  services/horizon/internal/test/scenarios/order_books_310-core.sql
  services/horizon/internal/test/scenarios/order_books_310-horizon.sql
  services/horizon/internal/test/scenarios/pathed_payment-core.sql
  services/horizon/internal/test/scenarios/pathed_payment-horizon.sql
  services/horizon/internal/test/scenarios/paths-core.sql
  services/horizon/internal/test/scenarios/paths-horizon.sql
  services/horizon/internal/test/scenarios/self_send-core.sql
  services/horizon/internal/test/scenarios/self_send-horizon.sql
  services/horizon/internal/test/scenarios/send_to_issuer-core.sql
  services/horizon/internal/test/scenarios/send_to_issuer-horizon.sql
  services/horizon/internal/test/scenarios/set_options-core.sql
  services/horizon/internal/test/scenarios/set_options-horizon.sql
  services/horizon/internal/test/scenarios/trades-core.sql
  services/horizon/internal/test/scenarios/trades-horizon.sql
Labels: in progress

#419 add support for go 1.10, remove support for go 1.7
  .travis.yml
  services/horizon/README.md
Labels: in progress

#420 remove redundant travis-ci build
  .travis.yml
Labels: in progress

#426 fixed race condition in friendbot test
  services/friendbot/init_friendbot.go
  services/friendbot/internal/friendbot.go
  services/friendbot/internal/friendbot_test.go
Labels: in progress
