Repository stellar/go, pull requests merged in 2019-11, with the labels that each got.

#1897 services/horizon/internal/actions: Update strict send path action to use query structs.
  protocols/horizon/main.go
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/asset.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/query_params.go
  services/horizon/internal/actions/validators.go
  services/horizon/internal/actions/validators_test.go
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/actions_root.go
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/resourceadapter/root.go
  services/horizon/internal/resourceadapter/root_test.go
  xdr/asset.go
  xdr/asset_test.go
Labels: cla: yes

#1901 services/horizon/internal/actions: Update strict receive path action to use query struct.
  protocols/horizon/main.go
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/actions_root.go
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/resourceadapter/root.go
  services/horizon/internal/resourceadapter/root_test.go
Labels: cla: yes

#1906 services/horizon: Fix `AccountsForSigner` to remove preauth tx signer
  services/horizon/CHANGELOG.md
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1905 support/env: replace os.Exit(1) with panic
  support/env/env.go
  support/env/env_test.go
Labels: cla: yes

#1910 Merge release-horizon-v0.22.2 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1907 keypair: add MustRandom
  keypair/main.go
  keypair/main_test.go
Labels: cla: yes

#1908 txnbuild: add GetSourceAccount to all operations
  txnbuild/account_merge.go
  txnbuild/allow_trust.go
  txnbuild/bump_sequence.go
  txnbuild/change_trust.go
  txnbuild/create_account.go
  txnbuild/create_passive_offer.go
  txnbuild/inflation.go
  txnbuild/manage_buy_offer.go
  txnbuild/manage_data.go
  txnbuild/manage_offer.go
  txnbuild/operation.go
  txnbuild/path_payment.go
  txnbuild/path_payment_strict_send.go
  txnbuild/payment.go
  txnbuild/set_options.go
Labels: cla: yes, txnbuild

#1909 protocols/horizon/effects: Add UnmarshalJSON to SequenceBumped.
  clients/horizonclient/effect_request_test.go
  protocols/horizon/effects/main.go
Labels: cla: yes

#1913 docs: deprecate the main.go/internal.go Horizon convention
  README.md
Labels: cla: yes, horizon

#1900 exp/hubble: pretty print state changes from history archives
  exp/hubble/cmd/main.go
  exp/hubble/pipeline.go
  exp/hubble/pretty_printers.go
  exp/hubble/processors.go
Labels: cla: yes

#1922 exp/hubble: print state changes using stx and goxdr
  exp/hubble/cmd/main.go
  exp/hubble/pipeline.go
  exp/hubble/pretty_printers.go
  exp/hubble/processors.go
  exp/hubble/serializers.go
  go.list
  go.mod
  go.sum
Labels: Hubble, cla: yes

#1923 .circleci: Remove ingest state diff job from CircleCI
  .circleci/config.yml
Labels: cla: yes

#1925 services/horizon: Clean and update CHANGELOG for 0.23.0
  services/horizon/CHANGELOG.md
Labels: cla: yes

#1927 Fix invalid account params message.
  services/horizon/internal/actions/account.go
Labels: cla: yes

#1929 protocols/horizon: Update "Action needed" tags
  protocols/horizon/effects/main.go
  protocols/horizon/main.go
  protocols/horizon/operations/main.go
Labels: cla: yes

#1917 services/horizon/internal/expingest: Implement state verifier for order book graph
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1930 services/horizon/internal/actions: Fix asset issuer does not exist bug in /assets endpoint
  services/horizon/internal/actions/asset.go
  services/horizon/internal/actions/asset_test.go
Labels: cla: yes

#1914 exp/ingest/ledgerbackend: Fix index out of range error in GetLatestLedgerSequence()
  exp/ingest/ledgerbackend/database_backend.go
  services/horizon/internal/expingest/database_backend_test.go
Labels: cla: yes

#1921 horizonclient: Remove deprecated fee_paid field from Transaction
  clients/horizon/main_test.go
  clients/horizonclient/main_test.go
  clients/horizonclient/transaction_request_test.go
  protocols/horizon/main.go
  protocols/horizon/main_test.go
  services/horizon/internal/resourceadapter/operations_test.go
  services/horizon/internal/resourceadapter/transaction.go
  services/horizon/internal/resourceadapter/transaction_test.go
Labels: cla: yes

#1915 protocols/horizon: Add custom UnmarshalJSON to struct with int64 fields.
  clients/horizonclient/effect_request_test.go
  clients/horizonclient/offer_request_test.go
  clients/horizonclient/operation_request_test.go
  clients/horizonclient/trade_aggregation_request_test.go
  protocols/horizon/base/main.go
  protocols/horizon/effects/main.go
  protocols/horizon/main.go
  protocols/horizon/operations/main.go
Labels: cla: yes

#1935 services/horizon: Use http.NewServeMux to create mux
  services/horizon/internal/app.go
Labels: cla: yes, horizon

#1931 add PR links to 0.23 Horizon changelog
  services/horizon/CHANGELOG.md
Labels: cla: yes

#1936 services/horizon/internal/expingest/processors: Only process authorized trustlines when updating asset stats
  services/horizon/internal/actions/asset.go
  services/horizon/internal/actions/asset_test.go
  services/horizon/internal/db2/history/asset_stats.go
  services/horizon/internal/db2/history/asset_stats_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/asset_stats_set.go
  services/horizon/internal/expingest/processors/asset_stats_set_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
Labels: cla: yes

#1939 services/horizon: Bump expingest version
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes, horizon

#1940 services/horizon: Truncate exp_asset_stats table when reingesting state
  services/horizon/internal/db2/history/main.go
Labels: cla: yes, horizon

#1942 services/horizon/internal/render/sse: Send bye bye event before exiting a StreamHandler
  services/horizon/internal/render/sse/stream_handler.go
  services/horizon/internal/render/sse/stream_handler_test.go
Labels: cla: yes

#1944 .circleci: remove go mod checks for go 1.12
  .circleci/config.yml
Labels: cla: yes

#1918 services/horizon/internal/expingest: Emit error log after 3 failed attempts to validate state
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipelines.go
Labels: cla: yes

#1951 services/horizon/internal/docs: Remove reference to operation_fee_stats.
  services/horizon/internal/docs/reference/endpoints/fee-stats.md
Labels: cla: yes

#1932 exp/hubble: write entries to elasticsearch
  exp/hubble/cmd/main.go
  exp/hubble/pipeline.go
  exp/hubble/processors.go
  exp/hubble/serializers.go
  go.list
  go.mod
  go.sum
Labels: cla: yes

#1957 Merge release-horizon-v0.23.1 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/app.go
Labels: cla: yes

#1958 services/federation: fix changelog for v0.2.1
  services/federation/CHANGELOG.md
Labels: cla: yes

#1959 services/keystore: update changelog to signal current revision as v1.2.0
  services/keystore/CHANGELOG.md
Labels: cla: yes

#1961 services/friendbot: set version for release v0.0.2
  services/friendbot/CHANGELOG.md
Labels: cla: yes

#1960 services/federation: set version on changelog for v0.3.0
  services/federation/CHANGELOG.md
Labels: cla: yes

#1962 services/ticker: set version for release v1.2.0
  services/ticker/CHANGELOG.md
Labels: cla: yes

#1966 services/{bridge,compliance}: update changelogs for release 0.0.33
  services/bridge/CHANGELOG.md
  services/compliance/CHANGELOG.md
Labels: cla: yes

#1947 tools/horizon-cmp: Remove unnecessary panics, update temp folder names
  tools/horizon-cmp/internal/response.go
  tools/horizon-cmp/main.go
Labels: cla: yes, horizon

#1948 doc: make README inviting
  README.md
Labels: cla: yes

#1953 services/horizon: Rename `OperationFeeStats` to `FeeStats`
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions_operation_fee_stats.go
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/app.go
  services/horizon/internal/db2/history/operation.go
  services/horizon/internal/main_generated.go
  services/horizon/internal/web.go
Labels: cla: yes

#1971 doc: link Stellar logo in header
  README.md
Labels: cla: yes

#1973 services/horizon/internal: Fix index out of range for requests with empty named url params.
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
Labels: cla: yes

#1899 support/historyarchive: Provide mechanism for retrying XDR stream errors
  exp/ingest/adapters/history_archive_adapter.go
  exp/ingest/adapters/history_archive_adapter_test.go
  exp/ingest/io/single_ledger_state_reader.go
  exp/ingest/io/single_ledger_state_reader_test.go
  exp/ingest/live_session.go
  exp/ingest/main.go
  exp/ingest/single_ledger_session.go
  exp/tools/dump-ledger-state/main.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/reporter.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/init.go
  support/historyarchive/xdrstream.go
  support/historyarchive/xdrstream_test.go
  tools/archive-reader/archive_reader.go
Labels: cla: yes

#1972 exp/pipeline: Graceful shutdown of Pipeline
  exp/ingest/live_session.go
  exp/ingest/single_ledger_session.go
  exp/support/pipeline/main.go
  exp/support/pipeline/pipeline.go
  exp/support/pipeline/pipeline_test.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/reporter.go
Labels: cla: yes, horizon

#1949 exp/ingest: Add processor to ingest ledger headers
  exp/ingest/ledgerbackend/mock_database_backend.go
  services/horizon/internal/db2/history/ledger.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/db2/history/mock_q_ledgers.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/26_exp_history_ledgers.sql
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1968 exp/hubble: create processor that only stores current ledger state
  exp/hubble/cmd/main.go
  exp/hubble/pipeline.go
  exp/hubble/processors.go
  exp/hubble/schema.go
  exp/hubble/schema_factory.go
  exp/hubble/schema_factory_test.go
  go.mod
Labels: Hubble, cla: yes

#1988 services/horizon: Rollback DB transaction in case of errors in the pipeline pre-hook
  services/horizon/internal/expingest/pipelines.go
Labels: cla: yes

#1984 exp/ingest/io: Ignore PROTOCOL_ERROR when retrying xdr streams
  exp/ingest/io/single_ledger_state_reader.go
  exp/ingest/io/single_ledger_state_reader_test.go
  support/historyarchive/xdrstream.go
Labels: cla: yes

#1978 services/horizon/internal/expingest: Graceful shutdown StateVerifier
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/run_ingestion_test.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1964 services/horizon/internal: Add fee_charged and max_fee to /fee_stats endpoint
  protocols/horizon/main.go
  services/horizon/internal/actions_operation_fee_stats.go
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/app.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/operation.go
  services/horizon/internal/operationfeestats/main.go
Labels: cla: yes

#1987 services/horizon: Improve performance of AssetStats processor
  services/horizon/CHANGELOG.md
  services/horizon/internal/expingest/processors/asset_stats_set.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
Labels: cla: yes, horizon
