Repository stellar/go, pull requests merged in 2019-12, with the labels that each got.

#1977 all: Use context from session in sqlx functions
  services/horizon/internal/ingest/asset_stat_test.go
  services/horizon/internal/ingest/ingestion_test.go
  services/horizon/internal/middleware.go
  services/horizon/internal/web.go
  services/ticker/internal/tickerdb/main.go
  services/ticker/internal/tickerdb/queries_asset_test.go
  services/ticker/internal/tickerdb/queries_issuer_test.go
  services/ticker/internal/tickerdb/queries_market_test.go
  services/ticker/internal/tickerdb/queries_orderbook_test.go
  services/ticker/internal/tickerdb/queries_trade_test.go
  support/db/batch_insert_builder_test.go
  support/db/delete_builder_test.go
  support/db/get_builder_test.go
  support/db/insert_builder_test.go
  support/db/main.go
  support/db/main_test.go
  support/db/select_builder_test.go
  support/db/session.go
  support/db/session_test.go
Labels: cla: yes

#1991 services/horizon/internal/docs: Update /fee_stats with max_fee and fee_charged.
  services/horizon/internal/docs/reference/endpoints/fee-stats.md
Labels: cla: yes

#1992 services/horizon: Fix ledger processor when not ingesting into a DB
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
Labels: cla: yes

#1993 services/horizon: Graceful shutdown when session errors
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#1995 support/db: Return ErrCancelled when query cancelled
  services/horizon/internal/render/problem/problem.go
  services/horizon/internal/web.go
  support/db/main.go
  support/db/session.go
Labels: cla: yes

#1996 Update horizon-cmp README.
  tools/horizon-cmp/README.md
Labels: cla: yes

#1998 services/horizon/render/problem: Change Cancelled to Service Unavailable
  services/horizon/internal/render/problem/problem.go
  services/horizon/internal/web.go
Labels: cla: yes, horizon

#1999 xdr: get address from AccountId without panic
  xdr/account_id.go
Labels: cla: yes

#2001 Use errors.Wrap to help debugging.
  services/horizon/internal/actions/account.go
Labels: cla: yes

#2000 xdr: get entry from ledger entry change
  xdr/ledger_entry_change.go
Labels: cla: yes

#2008 services/horizon/internal: Use registered errors to recover from errors in streaming.
  services/horizon/internal/render/sse/stream.go
  services/horizon/internal/render/sse/stream_test.go
  support/render/problem/problem.go
  support/render/problem/problem_test.go
Labels: cla: yes

#2012 Remove custom handler for sql.ErrNoRows in stream.
  services/horizon/internal/render/sse/stream.go
  services/horizon/internal/render/sse/stream_test.go
Labels: cla: yes

#2009 services/horizon/internal: Fix ParseFloat bug in /fee_stats
  services/horizon/internal/actions_operation_fee_stats.go
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/app.go
  services/horizon/internal/operationfeestats/main.go
Labels: cla: yes

#2020 services/compliance: fix broken link in README
  services/compliance/README.md
Labels: cla: yes

#2023 services/horizon: Pass errors to problem.Render in ExperimentalIngestionMiddleware
  services/horizon/internal/middleware.go
Labels: cla: yes, horizon

#1989 Update Horizon 0.24.0 CHANGELOG
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2024 support/db: Support concurrent queries in a transaction
  services/horizon/internal/expingest/main.go
  support/db/main.go
  support/db/session.go
  support/db/session_test.go
Labels: cla: yes, horizon

#1985 exp/hubble: convert schema factory tests to table-based
  exp/hubble/helper_functions_test.go
  exp/hubble/processors.go
  exp/hubble/schema_factory.go
  exp/hubble/schema_factory_test.go
Labels: Hubble, cla: yes

#2032 xdr: get address from signer key without panic
  xdr/signer_key.go
  xdr/signer_key_test.go
Labels: cla: yes

#2036 doc: change horizon query port
  services/horizon/internal/docs/quickstart.md
Labels: cla: yes

#2040 exp/tools/dump-ledger-state: Use @horizon-team in slack alert
  exp/tools/dump-ledger-state/docker-entrypoint.sh
Labels: cla: yes

#2033 keypair: add ParseFull function
  keypair/main.go
  keypair/main_test.go
Labels: cla: yes

#2042 support/config: simplify initing and setting multiple ConfigOptions
  services/horizon/cmd/root.go
  support/config/config_option.go
Labels: cla: yes

#2041 support/config: move viper bindpflag into init
  services/horizon/cmd/root.go
  support/config/config_option.go
Labels: cla: yes

#2004 Add LedgerEntryChangeCache
  exp/ingest/errors/main.go
  exp/ingest/io/ledger_entry_change_cache.go
  exp/ingest/io/ledger_entry_change_cache_test.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/verify/main.go
  exp/ingest/verify/main_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/accounts_data_processor_test.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
  services/horizon/internal/expingest/verify.go
  xdr/ledger_entry_change.go
  xdr/ledger_key.go
Labels: cla: yes

#2047 .circleci: Fix circleci publish_latest_horizon_docker_image job
  .circleci/config.yml
Labels: cla: yes

#2044 keypair: make simple to get FromAddress from any KP
  keypair/from_address.go
  keypair/full.go
  keypair/main.go
  keypair/main_test.go
Labels: cla: yes

#2049 Fix circleci for 0.24.1 release
  .circleci/config.yml
Labels: cla: yes

#2050 exp/ingest: Fix fee and transaction meta processing
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/ledger_transaction_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes, horizon

#2053 support/render/problem: add and update docs
  support/render/problem/problem.go
Labels: cla: yes

#2055 services/horizon/internal/expingest/main.go: Trim experimental ingestion historical data when starting ingestion
  services/horizon/internal/db2/history/ledger.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipeline_hooks_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/run_ingestion_test.go
Labels: cla: yes

#2051 support/http: remove behind proxy option for muxes
  services/bridge/main.go
  services/compliance/main.go
  services/federation/main.go
  services/friendbot/main.go
  support/http/mux.go
Labels: cla: yes

#2060 support/render/httpjson: add RenderStatus for rendering with non-200 status codes
  support/render/httpjson/io.go
  support/render/httpjson/io_test.go
Labels: cla: yes

#2058 exp/ingest/pipeline: Fix pipeline data race during shutdown
  exp/ingest/live_session.go
  exp/support/pipeline/pipeline.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/run_ingestion_test.go
Labels: cla: yes, horizon

#2059 services/horizon/internal/expingest: Fix deadlock in experimental ingestion
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#2062 services/horizon/CHANGELOG.md: Add changelog for v0.24.1 release
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2065 txnbuild: remove redundant ok from internal verify functions
  txnbuild/transaction.go
  txnbuild/transaction_test.go
Labels: cla: yes

#2064 services/ticker: add test logs to identify inputs that make test flaky
  services/ticker/internal/tickerdb/queries_asset_test.go
Labels: cla: yes

#2056 Merge horizon v0.24.1 into master
  exp/ingest/errors/main.go
  exp/ingest/io/ledger_entry_change_cache.go
  exp/ingest/io/ledger_entry_change_cache_test.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/ledger_transaction_test.go
  exp/ingest/live_session.go
  exp/ingest/verify/main.go
  exp/ingest/verify/main_test.go
  exp/support/pipeline/pipeline.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/history/ledger.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipeline_hooks_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/accounts_data_processor_test.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
  services/horizon/internal/expingest/run_ingestion_test.go
  services/horizon/internal/expingest/verify.go
  xdr/ledger_entry_change.go
  xdr/ledger_key.go
Labels: cla: yes

#2067 all: update excon to 0.71.0
  Gemfile.lock
Labels: cla: yes

#2070 txnbuild: check tx.xdrEnvelope first before other checks
  txnbuild/transaction.go
Labels: cla: yes

#2069 keypair: add ParseAddress
  keypair/main.go
  keypair/main_test.go
Labels: cla: yes

#2073 services/horizon: Batch Upsert Accounts and Trust Lines
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_accounts.go
  services/horizon/internal/db2/history/mock_q_trust_lines.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
Labels: cla: yes

#2037 services/horizon/internal/expingest: Transaction processor
  exp/ingest/io/ledger_transaction.go
  services/horizon/internal/db2/history/ingestion.go
  services/horizon/internal/db2/history/ingestion_test.go
  services/horizon/internal/db2/history/ledger.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_participants.go
  services/horizon/internal/db2/history/mock_q_transactions.go
  services/horizon/internal/db2/history/mock_transactions_batch_insert_builder.go
  services/horizon/internal/db2/history/participants.go
  services/horizon/internal/db2/history/participants_test.go
  services/horizon/internal/db2/history/transaction.go
  services/horizon/internal/db2/history/transaction_batch_insert_builder.go
  services/horizon/internal/db2/history/transaction_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/27_exp_history_transactions.sql
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipeline_hooks_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/orderbook_processor.go
  services/horizon/internal/expingest/processors/participants_processor.go
  services/horizon/internal/expingest/processors/participants_processor_test.go
  services/horizon/internal/expingest/processors/transactions_filter_processor.go
  services/horizon/internal/expingest/processors/transactions_filter_processor_test.go
  services/horizon/internal/expingest/processors/transactions_processor.go
  services/horizon/internal/expingest/processors/transactions_processor_test.go
  services/horizon/internal/expingest/run_ingestion_test.go
  services/horizon/internal/init.go
  services/horizon/internal/toid/main.go
  support/db/batch_insert_builder_test.go
Labels: cla: yes

#2075 support/http/httpdecode: move http decoding to its own package
  support/http/httpdecode/httpdecode.go
  support/http/httpdecode/httpdecode_test.go
  support/render/httpjson/handler.go
  support/render/httpjson/io.go
Labels: cla: yes

#2078 support/http/httpdecode: add funcs for form and form+json decoding
  support/http/httpdecode/httpdecode.go
  support/http/httpdecode/httpdecode_test.go
Labels: cla: yes

#2043 services/horizon/internal/expingest: Operations processor
  services/horizon/internal/db2/history/ingestion.go
  services/horizon/internal/db2/history/ingestion_test.go
  services/horizon/internal/db2/history/mock_operation_participant_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_operations_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_q_operations.go
  services/horizon/internal/db2/history/mock_q_participants.go
  services/horizon/internal/db2/history/operation.go
  services/horizon/internal/db2/history/operation_batch_insert_builder.go
  services/horizon/internal/db2/history/operation_batch_insert_builder_test.go
  services/horizon/internal/db2/history/operation_participant_batch_insert_builder.go
  services/horizon/internal/db2/history/operation_participant_batch_insert_builder_test.go
  services/horizon/internal/db2/history/operation_test.go
  services/horizon/internal/db2/history/participants.go
  services/horizon/internal/db2/history/participants_test.go
  services/horizon/internal/db2/history/transaction.go
  services/horizon/internal/db2/history/transaction_operation_wrapper.go
  services/horizon/internal/db2/history/transaction_operation_wrapper_test.go
  services/horizon/internal/db2/history/transaction_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/28_exp_history_operations.sql
  services/horizon/internal/expingest/pipeline_hooks_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/operations_processor_test.go
  services/horizon/internal/expingest/processors/participants_processor.go
  services/horizon/internal/expingest/processors/participants_processor_test.go
Labels: cla: yes

#2074 exp/services/webauth: add SEP-10 v1.2.0 implementation
  exp/services/webauth/README.md
  exp/services/webauth/internal/commands/genjwtkey.go
  exp/services/webauth/internal/commands/serve.go
  exp/services/webauth/internal/serve/challenge.go
  exp/services/webauth/internal/serve/challenge_test.go
  exp/services/webauth/internal/serve/errors.go
  exp/services/webauth/internal/serve/errors_test.go
  exp/services/webauth/internal/serve/serve.go
  exp/services/webauth/internal/serve/token.go
  exp/services/webauth/internal/serve/token_test.go
  exp/services/webauth/main.go
  exp/support/jwtkey/jwtkey.go
  exp/support/jwtkey/jwtkey_test.go
  go.list
  go.mod
  go.sum
Labels: cla: yes

#2080 services/keystore: use cors handler like our other apps
  services/keystore/api.go
Labels: cla: yes

#2079 services/horizon/internal: Move transaction operation wrapper to operation processor
  services/horizon/internal/db2/history/ingestion_test.go
  services/horizon/internal/db2/history/mock_operations_batch_insert_builder.go
  services/horizon/internal/db2/history/operation_batch_insert_builder.go
  services/horizon/internal/db2/history/operation_batch_insert_builder_test.go
  services/horizon/internal/db2/history/operation_participant_batch_insert_builder.go
  services/horizon/internal/db2/history/operation_participant_batch_insert_builder_test.go
  services/horizon/internal/db2/history/operation_test.go
  services/horizon/internal/db2/history/transaction_operation_wrapper.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/operations_processor_test.go
  services/horizon/internal/expingest/processors/participants_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/test/transactions/main.go
Labels: cla: yes
