Repository stellar/go, pull requests merged in 2019-10, with the labels that each got.

#1801 services/horizon: Remove `CREATE EXTENSION` from initial schema
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/1_initial_schema.sql
Labels: horizon

#1811 Horizon protocol v12
  protocols/horizon/effects/main.go
  protocols/horizon/main.go
  protocols/horizon/operations/main.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions_payment_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/ingest/participants/main.go
  services/horizon/internal/ingest/participants/main_test.go
  services/horizon/internal/ingest/session_test.go
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/paths_strict_send-core.sql
  services/horizon/internal/test/scenarios/paths_strict_send-horizon.sql
  services/horizon/internal/test/scenarios/paths_strict_send.rb
Labels: cla: yes, horizon

#1817 txnbuild: support protocol 12
  txnbuild/CHANGELOG.md
  txnbuild/example_test.go
  txnbuild/path_payment.go
  txnbuild/path_payment_test.go
Labels: cla: yes

#1826 horizon/ingest: Fix ingesting failed path payment operations
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/ingest/session.go
  services/horizon/internal/ingest/session_test.go
Labels: cla: yes

#1810 services/horizon/internal/db2/history: Asset stats ingestion
  services/horizon/internal/db2/history/asset_stats.go
  services/horizon/internal/db2/history/asset_stats_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_asset_stats.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/23_exp_asset_stats.sql
  services/horizon/internal/expingest/BETA_TESTING.md
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/asset_stats_set.go
  services/horizon/internal/expingest/processors/asset_stats_set_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#1827 services/horizon/internal/actions: Refactor accounts to use new actions system.
  services/horizon/internal/action.go
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions_account_test.go
  services/horizon/internal/handler.go
  services/horizon/internal/urlparams.go
  services/horizon/internal/web.go
Labels: cla: yes

#1833 Document how to create new migrations in Horizon.
  services/horizon/internal/docs/notes_for_developers.md
Labels: cla: yes

#1834 keystore/cmd: improve migrate down command
  services/keystore/cmd/keystored/README.md
  services/keystore/cmd/keystored/main.go
Labels: cla: yes

#1830 services/horizon/internal/actions: Add latest ingested ledger in experimental ingestion endpoints
  exp/orderbook/batch.go
  exp/orderbook/graph.go
  exp/orderbook/graph_test.go
  exp/tools/horizon-demo/pipelines.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/action_offers_expingest_test.go
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/orderbook.go
  services/horizon/internal/actions/orderbook_test.go
  services/horizon/internal/actions/session.go
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/context/context_key.go
  services/horizon/internal/expingest/load_orderbook_graph_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/orderbook_processor_test.go
  services/horizon/internal/handler.go
  services/horizon/internal/middleware.go
  services/horizon/internal/middleware_test.go
  services/horizon/internal/paths/main.go
  services/horizon/internal/simplepath/finder.go
  services/horizon/internal/simplepath/finder_test.go
  services/horizon/internal/simplepath/inmemory.go
  services/horizon/internal/stream_handler_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#1837 services/horizon/internal/expingest: Execute all ledger processors in one node
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
Labels: cla: yes

#1823 services/keystore: Add Dockerfile and related Makefile
  Makefile
  services/keystore/Makefile
  services/keystore/cmd/keystored/README.md
  services/keystore/docker/Dockerfile
Labels: cla: yes

#1819 services/horizon: Add accounts and account data to ingestion pipeline
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/ledger_transaction_test.go
  exp/tools/horizon-demo/database_processor.go
  exp/tools/horizon-demo/orderbook_processor.go
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/account_data_test.go
  services/horizon/internal/db2/history/account_data_value.go
  services/horizon/internal/db2/history/account_signers.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_batch_insert_builder.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_accounts_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_q_accounts.go
  services/horizon/internal/db2/history/mock_q_data.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/24_accounts.sql
  services/horizon/internal/expingest/BETA_TESTING.md
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/expingest/processors/accounts_data_processor_test.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/orderbook_processor.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
  services/horizon/internal/expingest/verify.go
  xdr/account_entry.go
Labels: cla: yes

#1843 support/clock,clients/horizonclient: add a mockable clock
  clients/horizonclient/client.go
  clients/horizonclient/internal.go
  clients/horizonclient/main.go
  clients/horizonclient/main_test.go
  support/clock/clocktest/fixed.go
  support/clock/clocktest/fixed_test.go
  support/clock/main.go
  support/clock/main_test.go
Labels: cla: yes, maintenance

#1854 changelog fixup
  services/horizon/CHANGELOG.md
Labels: cla: yes

#1824 services/horizon/internal/actions: Implement experimental ingestion asset stats endpoint
  services/horizon/internal/actions/asset.go
  services/horizon/internal/actions/asset_test.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/resourceadapter/asset_stat.go
  services/horizon/internal/resourceadapter/asset_stat_test.go
  services/horizon/internal/web.go
  xdr/account_id.go
  xdr/asset.go
Labels: cla: yes

#1846 services/horizon/internal/actions: Move get offer by id endpoint to actions package
  services/horizon/internal/action.go
  services/horizon/internal/action_offers_expingest_test.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/handler.go
  services/horizon/internal/urlparams.go
  services/horizon/internal/web.go
Labels: cla: yes

#1857 services/horizon: Use percentile_disc in fee stats query
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/db2/history/operation.go
Labels: cla: yes, horizon

#1847 services/horizon/internal, services/horizon/internal/expingest: Ingestion readiness check
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions_account_test.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/pipeline_hooks_test.go
  services/horizon/internal/expingest/pipelines.go
  services/horizon/internal/middleware.go
  services/horizon/internal/middleware_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#1849 exp/tools/dump-ledger-state, services/horizon/docker: Update quorum set in stellar core docker containers
  exp/tools/dump-ledger-state/docker-entrypoint.sh
  exp/tools/dump-ledger-state/stellar-core.cfg
  services/horizon/docker/docker-compose.yml
  services/horizon/docker/stellar-core-pubnet.env
Labels: cla: yes

#1863 exp/orderbook: Fix bug in strict send path finding search
  exp/orderbook/dfs.go
  exp/orderbook/graph.go
  exp/orderbook/graph_test.go
  services/horizon/CHANGELOG.md
Labels: cla: yes

#1755 services/horizon/internal/actions: Query struct with gorilla/schema and govalidators.
  go.list
  go.mod
  go.sum
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/query_params.go
  services/horizon/internal/actions/query_params_test.go
  services/horizon/internal/actions/validators.go
  services/horizon/internal/actions/validators_test.go
  xdr/account_id_test.go
  xdr/asset.go
  xdr/asset_test.go
Labels: cla: yes

#1866 Remove unnecessary whitespace and fix typo in godoc comments
  build/main.go
  clients/horizonclient/client.go
  clients/horizonclient/main.go
  clients/horizonclient/operation_request.go
Labels: cla: yes

#1859 Add resource adapter for history.AccountEntry
  protocols/horizon/main.go
  services/horizon/internal/db2/history/account_test.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/resourceadapter/account_entry.go
  services/horizon/internal/resourceadapter/account_entry_test.go
  services/horizon/internal/resourceadapter/balance.go
  services/horizon/internal/resourceadapter/balance_test.go
  xdr/account_flags.go
  xdr/account_flags_test.go
  xdr/trust_line_flags.go
  xdr/trust_line_flags_test.go
Labels: cla: yes

#1865 services/horizon/internal: Do not start repeatable read sessions for streaming endpoints
  services/horizon/internal/middleware.go
  services/horizon/internal/middleware_test.go
Labels: cla: yes

#1867 Make horizonclient examples fully qualified
  clients/horizonclient/asset_request_test.go
  clients/horizonclient/effect_request_test.go
  clients/horizonclient/examples_test.go
  clients/horizonclient/ledger_request_test.go
  clients/horizonclient/main_test.go
  clients/horizonclient/offer_request_test.go
  clients/horizonclient/operation_request_test.go
  clients/horizonclient/order_book_request_test.go
  clients/horizonclient/paths_request_test.go
  clients/horizonclient/root_test.go
  clients/horizonclient/trade_aggregation_request_test.go
  clients/horizonclient/trade_request_test.go
  clients/horizonclient/transaction_request_test.go
Labels: cla: yes

#1869 services/horizon: Set for empty referer
  services/horizon/internal/middleware.go
Labels: cla: yes

#1855 exp/tools/dump-ledger-state: Run dump ledger state against testnet
  .circleci/config.yml
  exp/tools/dump-ledger-state/docker-entrypoint.sh
  exp/tools/dump-ledger-state/main.go
  exp/tools/dump-ledger-state/run_test.sh
  exp/tools/dump-ledger-state/stellar-core-testnet.cfg
Labels: cla: yes

#1873 exp/tools/dump-ledger-state: Add extra flags to LATEST_LEDGER curl request
  exp/tools/dump-ledger-state/docker-entrypoint.sh
Labels: cla: yes

#1835 services/horizon/internal/actions: Find all accounts who are trustees to an asset.
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/query_params.go
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_data_test.go
  services/horizon/internal/db2/history/account_signers.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#1860 all: remove go vet shadow hack
  govet.sh
Labels: cla: yes

#1876 services/horizon/internal/actions: Update payload for "Accounts For Signers" end-point.
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_test.go
Labels: cla: yes

#1877 support/env: add env.Duration
  support/env/env.go
  support/env/env_test.go
Labels: cla: yes

#1879 support/env: use t.Fatal instead of panic in test
  support/env/env_test.go
Labels: cla: yes

#1862 exp/ingest: Process ledger upgrade meta
  exp/ingest/io/ledger_reader.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/main.go
  exp/ingest/io/mock_ledger_reader.go
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/main.go
  exp/ingest/pipeline/ledger_pipeline_test.go
  exp/ingest/pipeline/main.go
  exp/ingest/pipeline/wrappers.go
  exp/ingest/processors/csv_printer.go
  exp/ingest/processors/root_processor.go
  services/horizon/internal/expingest/processors/accounts_data_processor_test.go
  services/horizon/internal/expingest/processors/accounts_processor_test.go
  services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
  services/horizon/internal/expingest/processors/database_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/orderbook_processor.go
  services/horizon/internal/expingest/processors/orderbook_processor_test.go
  services/horizon/internal/expingest/processors/trust_lines_processor_test.go
Labels: cla: yes

#1880 support/env: make test helpers more specific and better named
  support/env/env_test.go
Labels: cla: yes

#1881 support/env: use readable presentation of time.Duration value in test
  support/env/env_test.go
Labels: cla: yes

#1845 services/keystore: Remove unnecessary Makefile target
  services/keystore/Makefile
  services/keystore/cmd/keystored/README.md
Labels: cla: yes

#1883 services/horizon/internal: Automate root url generation with query structs.
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions_root.go
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/resourceadapter/root.go
  services/horizon/internal/resourceadapter/root_test.go
Labels: cla: yes

#1868 services/horizon: Use new ingestion data in `/accounts/{account_id}`
  services/horizon/internal/action.go
  services/horizon/internal/action_test.go
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_data_test.go
  services/horizon/internal/db2/history/account_data_value.go
  services/horizon/internal/db2/history/account_signers.go
  services/horizon/internal/db2/history/account_signers_test.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/resourceadapter/account_entry.go
  services/horizon/internal/resourceadapter/signer.go
  xdr/account_entry.go
  xdr/account_thresholds.go
Labels: cla: yes

#1889 doc: lower the barrier-to-entry of writing great pr descriptions
  .github/pull_request_template.md
Labels: cla: yes

#1615 Add CircleCI step to publish horizon docker image for every release
  .circleci/config.yml
  services/horizon/docker/Dockerfile
Labels: cla: yes, horizon

#1895 services/bridge: fix links in readme
  services/bridge/README.md
Labels: bridge, cla: yes

#1896 services/compliance: fix links in readme
  services/compliance/README.md
Labels: cla: yes, compliance

#1893 services/horizon: Rename column names to be consistent
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/account_signers.go
  services/horizon/internal/db2/history/account_signers_batch_insert_builder.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_batch_insert_builder.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/22_trust_lines.sql
  services/horizon/internal/db2/schema/migrations/24_accounts.sql
  services/horizon/internal/db2/schema/migrations/25_expingest_rename_columns.sql
  services/horizon/internal/test/scenarios/base-core.sql
  services/horizon/internal/test/scenarios/base-horizon.sql
  services/horizon/internal/test/scenarios/bindata.go
Labels: cla: yes

#1891 services/horizon/internal/actions: Update asset filter on accounts
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/validators.go
  services/horizon/internal/actions/validators_test.go
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/docs/reference/endpoints/accounts.md
Labels: cla: yes
