Repository stellar/go, pull requests merged in 2020-10, with the labels that each got.

#3082 historyarchive: Check archive's network passphrase when getting HAS
  exp/ingest/ledgerbackend/captive_core_backend.go
  historyarchive/archive.go
  historyarchive/archive_test.go
  historyarchive/history_archive_state.go
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#3078 Add friendbot Dockerfile and Makefile
  Makefile
  services/friendbot/Makefile
  services/friendbot/docker/Dockerfile
Labels: cla: yes

#3086 xdr: Use underscore in JSON fields for claim predicate.
  services/horizon/internal/resourceadapter/operations_test.go
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#3087 txnbuild: Fix bug in parsing transactions with Protocol 14 operations
  clients/horizonclient/CHANGELOG.md
  txnbuild/CHANGELOG.md
  txnbuild/begin_sponsoring_future_reserves_test.go
  txnbuild/claim_claimable_balance_test.go
  txnbuild/create_claimable_balance.go
  txnbuild/create_claimable_balance_test.go
  txnbuild/end_sponsoring_future_reserves_test.go
  txnbuild/operation.go
  txnbuild/revoke_sponsorship_test.go
Labels: cla: yes

#3088 services/horizon: Wrap invalid cursor in claimable balances in problem.P
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/claimable_balance_test.go
  services/horizon/internal/db2/history/claimable_balances.go
Labels: cla: yes

#3091 services/horizon: Fix typo on cursor error and improve message.
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/claimable_balance_test.go
Labels: cla: yes

#3092 services/horizon/expingest: Change log message when history not consistent with state
  services/horizon/internal/expingest/orderbook.go
Labels: cla: yes

#3093 service/horizon: Add protocol version support check
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
Labels: cla: yes

#3094 support/render/problem: Silent errors only when LogNoErrors set
  support/render/problem/problem.go
Labels: cla: yes

#3083 services/horizon: Fix separation of concerns related to offers ingestion
  services/horizon/internal/action_offers_test.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/orderbook_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_q_offers.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/orderbook_test.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/offers_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/resourceadapter/offer.go
  support/db/main.go
  support/db/table.go
Labels: cla: yes

#3095 Merge master into release-horizon-v1.10.0
  Makefile
  clients/horizonclient/CHANGELOG.md
  services/friendbot/Makefile
  services/friendbot/docker/Dockerfile
  services/horizon/internal/action_offers_test.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/orderbook_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_q_offers.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/orderbook_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/main.go
  services/horizon/internal/expingest/processors/offers_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/resourceadapter/offer.go
  support/db/main.go
  support/db/table.go
  support/render/problem/problem.go
  txnbuild/CHANGELOG.md
  txnbuild/begin_sponsoring_future_reserves_test.go
  txnbuild/claim_claimable_balance_test.go
  txnbuild/create_claimable_balance.go
  txnbuild/create_claimable_balance_test.go
  txnbuild/end_sponsoring_future_reserves_test.go
  txnbuild/operation.go
  txnbuild/revoke_sponsorship_test.go
Labels: cla: yes

#3062 Removed service/bridge reference in README.md
  README.md
Labels: cla: yes

#3096 services/horizon: Insert signers's sponsorship information during state ingestion
  services/horizon/internal/expingest/processors/signer_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
Labels: cla: yes

#3097 Horizon 1.9.1 CHANGELOG
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3098 Merge release-horizon-v1.9.1 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/expingest/processors/signer_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
  services/horizon/internal/resourceadapter/operations_test.go
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#3100 services/horizon: Add claimable_balances table to state tables to truncate
  services/horizon/internal/db2/history/ingestion.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#3101 services/horizon: Refactor handling of stellar-core-binary-path
  services/horizon/cmd/db.go
  services/horizon/cmd/ingest.go
  services/horizon/cmd/root.go
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#3090 services/horizon: Improve sponsorship integration tests' running time & flexibility.
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes, maintenance

#3103 services/horizon: Add Go and process related metrics
  services/horizon/internal/app.go
  services/horizon/internal/init.go
Labels: cla: yes

#3107 services/horizon: Allow using captive core in integration tests
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3113 exp/services/webauth: remove the stellar.toml domain checks
  exp/services/webauth/README.md
  exp/services/webauth/cmd/serve.go
  exp/services/webauth/internal/serve/serve.go
Labels: cla: yes

#3114 services/horizon: Run integration tests nightly and include captive core
  .circleci/config.yml
Labels: cla: yes

#3106 services/horizon: Use local Horizon in integration tests
  .circleci/config.yml
  services/horizon/cmd/db.go
  services/horizon/cmd/ingest.go
  services/horizon/cmd/root.go
  services/horizon/cmd/serve.go
  services/horizon/internal/app.go
  services/horizon/internal/flags.go
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration/integration.go
  support/db/main.go
Labels: cla: yes

#3105 txnbuild: Adds a helper function to determine asset type from string.
  txnbuild/CHANGELOG.md
  txnbuild/helpers.go
  txnbuild/helpers_test.go
Labels: cla: yes

#3125 Merge release-horizon-v1.10.0 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/claimable_balance_test.go
  services/horizon/internal/app.go
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/ingestion.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/init.go
Labels: cla: yes

#3130 services/horizon/docker: Upgrade Stellar-Core to 14.1.1
  services/horizon/docker/Dockerfile
Labels: cla: yes

#3122 txnbuild: Add helper to calculate claimable balance IDs without submitting transactions.
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration/integration.go
  txnbuild/CHANGELOG.md
  txnbuild/transaction.go
Labels: cla: yes

#3108 txnbuild: implement SEP-10 v2.1.0
  exp/services/webauth/internal/serve/token_test.go
  txnbuild/CHANGELOG.md
  txnbuild/transaction.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3136 clients/horizonclient,txnbuild: update changelogs for v4.1.0
  clients/horizonclient/CHANGELOG.md
  txnbuild/CHANGELOG.md
Labels: cla: yes

#3135 Update stellartoml client
  clients/stellartoml/client.go
  clients/stellartoml/client_test.go
  clients/stellartoml/main.go
Labels: cla: yes

#3104 services/horizon/docker: Restore horizon container's captive core binary path
  services/horizon/docker/Dockerfile
Labels: cla: yes

#3137 services/horizon: Pass EnableCaptiveCore to config.
  .circleci/config.yml
  services/horizon/cmd/ingest.go
  services/horizon/internal/init.go
Labels: cla: yes

#3139 services/horizon: Bump max supported protocol version to 15
  services/horizon/CHANGELOG.md
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
Labels: cla: yes

#3138 Use --start-ledger and --start-hash in online captive core.
  historyarchive/archive.go
  historyarchive/mocks.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3142 txnbuild: Add unit test for zero-balance account creation
  txnbuild/operation_test.go
Labels: cla: yes

#3140 Merge release-horizon-v1.10.1 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/ingest/main.go
  services/horizon/internal/ingest/processor_runner_test.go
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
Labels: cla: yes

#3146 services/horizon: Fix Protocol 15 integration test
  services/horizon/internal/integration/protocol14_test.go
Labels: cla: yes

#3151 services/horizon/ingest: Don't try to set cursor if using captive core.
  services/horizon/internal/ingest/main.go
Labels: cla: yes

#3150 services/horizon: Make stellar core database URL optional if captive core is enabled.
  services/horizon/internal/flags.go
  services/horizon/internal/init.go
Labels: cla: yes

#3161 clients/stellarcore: Add Manual Close endpoint to Core's client
  clients/stellarcore/client.go
  clients/stellarcore/client_test.go
Labels: cla: yes

#3147 services/horizon: Change protocol version check error
  services/horizon/internal/ingest/processor_runner.go
  services/horizon/internal/ingest/processor_runner_test.go
Labels: cla: yes

#3148 services/horizon: Export ledger stats in /metrics, add claimable_balance to change stats
  ingest/io/stats_change_processor.go
  ingest/io/stats_change_processor_test.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/ingest/fsm.go
  services/horizon/internal/ingest/main.go
  services/horizon/internal/init.go
Labels: cla: yes

#3162 services/horizon: Make captive core runner more robust
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
  ingest/ledgerbackend/stellar_core_runner_posix.go
  ingest/ledgerbackend/stellar_core_runner_windows.go
Labels: cla: yes

#3160 services/horizon: Allow captive core to start from any ledger.
  exp/tools/captive-core-start-tester/main.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/ledger_backend.go
Labels: cla: yes

#3163 Merge captive-run-from into master
  exp/tools/captive-core-start-tester/main.go
  historyarchive/archive.go
  historyarchive/mocks.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/ledger_backend.go
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3167 services/horizon: Update integration tests to use MANUAL_CLOSE
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/test/integration/integration.go
Labels: cla: yes

#3127 services/horizon: Check state rebuild in state verification integration test
  .circleci/config.yml
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/test/integration/integration.go
Labels: cla: yes

#3168 all: Update go-xdr to the latest version
  go.list
  go.mod
  go.sum
Labels: cla: yes

#3165 txnbuild: Adds unit testable examples for Protocol 15 operations.
  txnbuild/example_test.go
Labels: cla: yes, docs, txnbuild

#3171 services/horizon: Add some manual-close improvements to integration tests
  services/horizon/internal/test/integration/integration.go
Labels: cla: yes

#3175 services/horizon/docker/verify-range: Bump stellar-core version.
  services/horizon/docker/verify-range/Dockerfile
Labels: cla: yes

#3166 xdr: Adds a helper to extract balance IDs from transaction results.
  services/horizon/internal/integration/protocol14_test.go
  txnbuild/helpers.go
  xdr/transaction_result.go
Labels: cla: yes

#3177 exp/tools/dump-ledger-state: Fix dump ledger state script
  exp/tools/dump-ledger-state/Dockerfile
  exp/tools/dump-ledger-state/README.md
  exp/tools/dump-ledger-state/diff_test.sh
  exp/tools/dump-ledger-state/dump_core_db.sh
  exp/tools/dump-ledger-state/main.go
Labels: cla: yes
