Repository stellar/go, pull requests merged in 2020-09, with the labels that each got.

#2951 services/horizon: Update effects processor for CAP 33
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/resourceadapter/effects.go
Labels: cla: yes

#2976 services/horizon: Fix small issues related to Protocol 14 API
  protocols/horizon/main.go
  protocols/horizon/operations/main.go
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/claimable_balance_test.go
  services/horizon/internal/resourceadapter/claimable_balances.go
  services/horizon/internal/resourceadapter/claimable_balances_test.go
Labels: cla: yes

#2978 xdr: Fix bug in json serliazation of claim predicates
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#2980 services/horizon: Protocol 14 operations' resource adapters
  protocols/horizon/operations/main.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/resourceadapter/operations.go
  services/horizon/internal/resourceadapter/operations_test.go
  xdr/json_test.go
Labels: cla: yes

#2981 services/horizon/txsub: Add Protocol 14 error codes
  services/horizon/internal/codes/main.go
Labels: cla: yes

#2983 services/horizon: Fix Protocol 14 operations resource adapter
  services/horizon/internal/resourceadapter/operations.go
Labels: cla: yes

#2984 services/horizon/txsub: Add Protocol 14 ops in ForOperationResult
  services/horizon/internal/codes/main.go
Labels: cla: yes

#2990 services/horizon: Do not error on missing BeginSponsoringOp
  services/horizon/internal/expingest/processors/operations_processor.go
Labels: cla: yes

#2995 services/horizon: Fix inner tx max fee DB constraint
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/40_fix_inner_tx_max_fee_constraint.sql
Labels: cla: yes

#2996 Merge release-horizon-v1.8.1 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/40_fix_inner_tx_max_fee_constraint.sql
Labels: cla: yes

#2993 services/horizon: Omit begin_sponsor detail of EndSponsoringFutureReserves if missing
  protocols/horizon/operations/main.go
Labels: cla: yes

#2994 services/horizon: Account for overlapping sandwiches in EndSponsoringFutureReserves
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
Labels: cla: yes

#3002 exp/services/recoverysigner: call database transaction `.Rollback()` when returning an error
  exp/services/recoverysigner/internal/account/db_store_add.go
  exp/services/recoverysigner/internal/account/db_store_add_test.go
Labels: cla: yes, vibrant

#2991 [WIP] services/horizon: Add integration tests for Claimable Balances.
  clients/horizonclient/claimable_balance_request.go
  clients/horizonclient/client.go
  clients/horizonclient/main.go
  protocols/horizon/main.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3003 exp/services/recoverysigner: call database transaction `.Rollback()` when returning an error from db_store_update
  exp/services/recoverysigner/internal/account/db_store_add_test.go
  exp/services/recoverysigner/internal/account/db_store_update.go
  exp/services/recoverysigner/internal/account/db_store_update_test.go
Labels: cla: yes, vibrant

#2999 services/horizon: Add basic integration test scenario for CAP23.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/txnbuild/create_claimable_balance.go
Labels: cla: yes

#3007 Add exported function comment.
  services/ticker/cmd/root.go
Labels: cla: yes

#3004 services/horizon/internal/expingest: Fix claim claimable balances effects processor.
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
Labels: cla: yes

#3005 Fix static check tests.
  services/horizon/internal/actions/claimable_balance_test.go
  services/horizon/internal/expingest/processors/claimable_balances_processor_test.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/test/integration.go
  services/horizon/internal/txnbuild/begin_sponsoring_future_reserves.go
  services/horizon/internal/txnbuild/claim_claimable_balance.go
  services/horizon/internal/txnbuild/cmd/demo/cmd/init.go
  services/horizon/internal/txnbuild/cmd/demo/cmd/reset.go
  services/horizon/internal/txnbuild/cmd/demo/cmd/root.go
  services/horizon/internal/txnbuild/cmd/demo/cmd/txerror.go
  services/horizon/internal/txnbuild/cmd/demo/main.go
  services/horizon/internal/txnbuild/cmd/demo/operations/demo.go
  services/horizon/internal/txnbuild/create_claimable_balance.go
  services/horizon/internal/txnbuild/end_sponsoring_future_reserves.go
  services/horizon/internal/txnbuild/examplehorizonclient/examplehorizonclient.go
  services/horizon/internal/txnbuild/transaction.go
Labels: cla: yes

#3010 services/horizon/internal/httpx: Fix TLS configuration
  services/horizon/CHANGELOG.md
  services/horizon/internal/httpx/server.go
Labels: cla: yes

#3006 services/horizon: Add integration tests that actually claim claimable balances
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
  services/horizon/internal/txnbuild/claim_claimable_balance.go
Labels: cla: yes

#3012 services/ticker: redesign API
  services/ticker/internal/actions_orderbook.go
  services/ticker/internal/actions_trade.go
  services/ticker/internal/gql/main.go
  services/ticker/internal/gql/resolvers_market.go
  services/ticker/internal/gql/resolvers_market_test.go
  services/ticker/internal/gql/static/bindata.go
  services/ticker/internal/gql/static/schema.gql
  services/ticker/internal/graphql_test.go
  services/ticker/internal/tickerdb/helpers.go
  services/ticker/internal/tickerdb/main.go
  services/ticker/internal/tickerdb/queries_market.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_asset_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_issuer_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_market_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_orderbook_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_trade_test.go
  services/ticker/internal/tickerdb/tickerdbtest/tickerdbtest.go
Labels: cla: yes

#3013 services/horizon: Extend CreateAccounts to take initial balance.
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3008 services/friendbot: fix #2271 (send on closed channel error)
  services/friendbot/init_friendbot.go
  services/friendbot/internal/friendbot_test.go
  services/friendbot/internal/minion.go
  services/friendbot/internal/minion_test.go
Labels: cla: yes

#3014 exp/services/recoverysigner: add comment to make the tests approach clearer about closing the dbTx
  exp/services/recoverysigner/internal/account/db_store_add_test.go
  exp/services/recoverysigner/internal/account/db_store_update_test.go
Labels: cla: yes, vibrant

#3016 services/horizon: Add integration test for invalid claimable balance operation.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3019 Fix dump-ledger-state Dockerfile
  exp/tools/dump-ledger-state/Dockerfile
Labels: cla: yes

#2998 services/horizon: Add state verifier integration tests connected to Protocol 14
  .circleci/config.yml
  protocols/horizon/main.go
  services/horizon/internal/actions/account_data.go
  services/horizon/internal/actions/root.go
  services/horizon/internal/db2/history/account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/resourceadapter/balance.go
  services/horizon/internal/resourceadapter/root.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3015 services/ticker: increase db test time tolerance
  services/ticker/internal/tickerdb/tickerdb_test/queries_market_test.go
Labels: cla: yes

#2967 {txnbuild, webauth}: support the SEP-10 V2
  exp/services/webauth/README.md
  exp/services/webauth/cmd/serve.go
  exp/services/webauth/internal/serve/challenge.go
  exp/services/webauth/internal/serve/challenge_test.go
  exp/services/webauth/internal/serve/serve.go
  exp/services/webauth/internal/serve/token.go
  exp/services/webauth/internal/serve/token_test.go
  txnbuild/CHANGELOG.md
  txnbuild/transaction.go
  txnbuild/transaction_challenge_example_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3023 services/horizon: Check more details when we test claiming a claimable balance.
  services/horizon/internal/integration/protocol14_test.go
Labels: cla: yes

#3024 services/horizon: Improve tests for account data sponsor and claimable balance helpers.
  services/horizon/internal/actions_data_test.go
  services/horizon/internal/db2/history/account_data_batch_insert_builder_test.go
  services/horizon/internal/db2/history/account_data_test.go
  services/horizon/internal/db2/history/claimable_balances_test.go
Labels: cla: yes

#3018 services/horizon: Add integration test for sponsored claimable balance.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
Labels: cla: yes

#3009 Override CircleCI builtin checkout command
  .circleci/config.yml
Labels: cla: yes

#3021 services/horizon: Add sponsorship and claimable balance effects
  protocols/horizon/effects/main.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
  services/horizon/internal/resourceadapter/effects.go
  services/horizon/internal/resourceadapter/transaction_result_codes.go
  xdr/account_entry.go
  xdr/account_entry_test.go
Labels: cla: yes

#3027 services/horizon/internal/httpx: Fix TLS configuration
  services/horizon/CHANGELOG.md
  services/horizon/internal/httpx/server.go
Labels: cla: yes

#3030 Revert PR #3009 as it breaks CircleCI runs in some cases
  .circleci/config.yml
Labels: cla: yes

#3028 Merge master into Protocol 14 branch
  exp/services/recoverysigner/internal/account/db_store_add.go
  exp/services/recoverysigner/internal/account/db_store_add_test.go
  exp/services/recoverysigner/internal/account/db_store_update.go
  exp/services/recoverysigner/internal/account/db_store_update_test.go
  exp/services/webauth/README.md
  exp/services/webauth/cmd/serve.go
  exp/services/webauth/internal/serve/challenge.go
  exp/services/webauth/internal/serve/challenge_test.go
  exp/services/webauth/internal/serve/serve.go
  exp/services/webauth/internal/serve/token.go
  exp/services/webauth/internal/serve/token_test.go
  exp/tools/dump-ledger-state/Dockerfile
  services/friendbot/init_friendbot.go
  services/friendbot/internal/friendbot_test.go
  services/friendbot/internal/minion.go
  services/friendbot/internal/minion_test.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/httpx/server.go
  services/ticker/internal/actions_orderbook.go
  services/ticker/internal/actions_trade.go
  services/ticker/internal/gql/main.go
  services/ticker/internal/gql/resolvers_market.go
  services/ticker/internal/gql/resolvers_market_test.go
  services/ticker/internal/gql/static/bindata.go
  services/ticker/internal/gql/static/schema.gql
  services/ticker/internal/graphql_test.go
  services/ticker/internal/tickerdb/helpers.go
  services/ticker/internal/tickerdb/main.go
  services/ticker/internal/tickerdb/queries_market.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_asset_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_issuer_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_market_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_orderbook_test.go
  services/ticker/internal/tickerdb/tickerdb_test/queries_trade_test.go
  services/ticker/internal/tickerdb/tickerdbtest/tickerdbtest.go
  txnbuild/CHANGELOG.md
  txnbuild/transaction.go
  txnbuild/transaction_challenge_example_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3025 services/horizon: Add sponsored signer to state verifier integration test.
  services/horizon/internal/integration/protocol14_state_verifier_test.go
Labels: cla: yes

#3026 services/horizon: Revamps existing integration tests to run faster & be more modular.
  .circleci/config.yml
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
  services/horizon/internal/txnbuild/create_claimable_balance.go
Labels: cla: yes

#3033 services/horizon: Add integration tests for predicates on claimable balances.
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/txnbuild/transaction_challenge_example_test.go
Labels: cla: yes

#3034 services/horizon: Update integration tests for cap 23 effects
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/txnbuild/transaction_challenge_example_test.go
Labels: cla: yes

#3038 services/horizon: Add Basic sponsorship integration test
  protocols/horizon/operations/main.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
Labels: cla: yes

#3039 Merge txnbuild 3.2.0 changes back into master
  clients/horizonclient/examples_test.go
  clients/horizonclient/main_test.go
  exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
  exp/services/webauth/internal/serve/challenge_test.go
  services/friendbot/internal/friendbot_test.go
  txnbuild/CHANGELOG.md
  txnbuild/change_trust_test.go
  txnbuild/example_test.go
  txnbuild/fee_bump_test.go
  txnbuild/helpers_test.go
  txnbuild/signers_test.go
  txnbuild/transaction.go
  txnbuild/transaction_fee_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3041 services/horizon: Add integration test to ensure double-claiming a CB won't work.
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
  services/horizon/internal/txnbuild/create_claimable_balance.go
Labels: cla: yes

#3040 Merge master into protocol 14 branch
  clients/horizonclient/examples_test.go
  clients/horizonclient/main_test.go
  exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
  exp/services/webauth/internal/serve/challenge_test.go
  services/friendbot/internal/friendbot_test.go
  txnbuild/CHANGELOG.md
  txnbuild/change_trust_test.go
  txnbuild/example_test.go
  txnbuild/fee_bump_test.go
  txnbuild/helpers_test.go
  txnbuild/signers_test.go
  txnbuild/transaction.go
  txnbuild/transaction_fee_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3036 services/horizon: Implement support for RevokeSponsorship in txnbuild
  services/horizon/internal/txnbuild/begin_sponsoring_future_reserves.go
  services/horizon/internal/txnbuild/helpers.go
  services/horizon/internal/txnbuild/revoke_sponsorship.go
  services/horizon/internal/txnbuild/revoke_sponsorship_test.go
Labels: Protocol 14, cla: yes, horizon

#3043 protocols/horizon: fix trade aggregation paging token
  protocols/horizon/main.go
  protocols/horizon/main_test.go
Labels: cla: yes

#3045 services/horizon: Add changelog entry for protocol 14 additions
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3042 Expand Sponsorhip integration tests and participants for RevokeSponsorship
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
Labels: cla: yes

#2870 clients/horizonclient: wrap errors relating to decoding responses
  clients/horizonclient/internal.go
Labels: cla: yes

#3047 services/horizon/integration: Update binary name to match new stellar:quickstart image.
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3044 all: update supported go version to 1.14 and 1.15
  .circleci/config.yml
  DEVELOPING.md
  README.md
  clients/horizonclient/CHANGELOG.md
  clients/horizonclient/README.md
  exp/services/market-tracker/README.md
  services/federation/CHANGELOG.md
  services/horizon/CHANGELOG.md
  services/horizon/docker/verify-range/dependencies
  services/horizon/internal/docs/admin.md
  services/horizon/internal/docs/developing.md
  services/keystore/CHANGELOG.md
  services/ticker/CHANGELOG.md
  txnbuild/CHANGELOG.md
  txnbuild/README.md
Labels: cla: yes

#3049 services/horizon: Fix variable shadowing in integration test tx submission
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3051 Avoid nils in signer sponsorship map
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/signers_processor.go
  xdr/account_entry.go
  xdr/account_entry_test.go
Labels: cla: yes

#3050 Fix sponsor ingestion bug and add Sponsored preauth signer integration test
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
Labels: cla: yes

#3032 Override CircleCI builtin checkout command
  .circleci/config.yml
Labels: cla: yes

#3056 Fix compilation error due to merge misalignment
  services/horizon/internal/expingest/processors/operations_processor.go
Labels: cla: yes

#3057 Improve circleci checkout workdir handling
  .circleci/config.yml
Labels: cla: yes

#3054 services/horizon: Improve integration test framework
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3052 exp/services/recoverysigner: do not set max idle db connections
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#3058 services/horizon: Consolidate two tests into one so that runtime is faster.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
Labels: cla: yes

#3060 Add data sponsoring integration test and fix Data effects
  protocols/horizon/effects/main.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/resourceadapter/effects.go
Labels: cla: yes

#3061 support/http: add ReadTimeout, WriteTimeout, IdleTimeout configs
  support/http/main.go
  support/http/main_test.go
Labels: cla: yes

#3064 protocols/horizon: Add last_modfied_time to claimable balance response
  protocols/horizon/main.go
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/resourceadapter/claimable_balances.go
  services/horizon/internal/resourceadapter/claimable_balances_test.go
Labels: cla: yes

#3063 xdr: Return RelBefore as a String instead of Number when representing in JSON.
  services/horizon/internal/resourceadapter/operations_test.go
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#3055 services/horizon: Improve predicate integration tests to run faster and do more validation.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3068 services/horizon: Fix data effect details not being ingested
  services/horizon/internal/resourceadapter/effects.go
Labels: cla: yes

#3066 services/horizon: Add sponsored trustline/offer integration test and expand data test
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  txnbuild/revoke_sponsorship.go
  txnbuild/revoke_sponsorship_test.go
Labels: cla: yes

#2933 services/horizon: Remove redundant test
  services/horizon/internal/expingest/processors/operations_processor_test.go
Labels: cla: yes

#3071 services/horizon: Remove signer from revoke_sponsorship participants
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
Labels: cla: yes

#3072 services/horizon: Expand CAP 33 integration tests and fix 500 error bug
  protocols/horizon/effects/main.go
  protocols/horizon/operations/main.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/resourceadapter/operations_test.go
  txnbuild/revoke_sponsorship.go
Labels: cla: yes

#3073 Merge master into protocol-14 branch
  .circleci/config.yml
  DEVELOPING.md
  README.md
  clients/horizonclient/CHANGELOG.md
  clients/horizonclient/README.md
  clients/horizonclient/internal.go
  exp/services/market-tracker/README.md
  exp/services/recoverysigner/internal/serve/serve.go
  protocols/horizon/main.go
  protocols/horizon/main_test.go
  services/federation/CHANGELOG.md
  services/horizon/CHANGELOG.md
  services/horizon/docker/verify-range/dependencies
  services/horizon/internal/docs/admin.md
  services/horizon/internal/docs/developing.md
  services/horizon/internal/expingest/processors/operations_processor_test.go
  services/keystore/CHANGELOG.md
  services/ticker/CHANGELOG.md
  support/http/main.go
  support/http/main_test.go
  txnbuild/CHANGELOG.md
  txnbuild/README.md
Labels: cla: yes

#3059 services/horizon: Improves test cleanup process in case of subtest panics.
  services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
  services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#3074 clients/horizonclient+txnbuild: Update CHANGELOGs for horizonclient 4.0 release
  clients/horizonclient/CHANGELOG.md
  txnbuild/CHANGELOG.md
Labels: cla: yes

#3077 services/horizon: Update v1.9.0 CHANGELOG with state rebuild info
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3080 services/horizon: Update state verifier tests to check the middle signer's sponsor
  services/horizon/internal/integration/protocol14_state_verifier_test.go
Labels: cla: yes
