Repository stellar/go, pull requests merged in 2020-08, with the labels that each got.

#2876 xdr: Regenerate XDR definitions.
  xdr/Stellar-transaction.x
  xdr/xdr_generated.go
Labels: cla: yes

#2874 services/horizon: Add Captive Stellar-Core doc
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#2873 exp/ingest/ledgerbackend: Update CaptiveStellarCore godoc
  exp/ingest/ledgerbackend/captive_core_backend.go
Labels: cla: yes

#2846 services/horizon: Refactor metrics, use Prometheus package
  go.mod
  services/horizon/internal/actions/metrics.go
  services/horizon/internal/app.go
  services/horizon/internal/app_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/httpx/middleware.go
  services/horizon/internal/httpx/router.go
  services/horizon/internal/httpx/server.go
  services/horizon/internal/init.go
  services/horizon/internal/logmetrics/main.go
  services/horizon/internal/logmetrics/main_test.go
  services/horizon/internal/txsub/system.go
  services/horizon/internal/txsub/system_test.go
Labels: cla: yes

#2878 Merge master into 1.7.0 release branch
  exp/ingest/doc.go
  exp/ingest/doc_test.go
  exp/ingest/io/main.go
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/main.go
  services/horizon/cmd/db.go
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#2879 services/horizon: Add Golang version to horizon version output
  services/horizon/cmd/version.go
Labels: cla: yes

#2877 services/horizon/internal/txsub: Fix false positive bad sequence error when submitting transactions
  services/horizon/internal/txsub/system.go
  services/horizon/internal/txsub/system_test.go
Labels: cla: yes

#2880 Update CHANGELOG for release 1.7.0
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2893 Revert "services/horizon: Limit time range to max of number of buckets in trades aggregation query (#2856)"
  services/horizon/internal/db2/history/trade_aggregation.go
  services/horizon/internal/db2/history/trade_aggregation_test.go
  support/time/main.go
Labels: cla: yes

#2894 xdr: Update XDR definitions with updated sponsoring op names
  xdr/Stellar-transaction.x
  xdr/xdr_generated.go
Labels: cla: yes

#2884 horizon: Add CAP0023 and CAP0033 related changes to Horizon database.
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/39_claimable_balances.sql
  services/horizon/internal/db2/schema/migrations/40_add_sponsor_to_state_tables.sql
  services/horizon/internal/db2/schema/migrations/41_add_num_sponsored_and_num_sponsoring_to_accounts.sql
Labels: cla: yes

#2895 services/horizon/db2: Check previous errors before checking if TradesQ.Page was called
  services/horizon/internal/db2/history/trade.go
Labels: cla: yes

#2899 services/horizon: Refactor IngestionQ methods to use xdr.LedgerEntry
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/asset_test.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/orderbook_test.go
  services/horizon/internal/actions_data_test.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/account_data_test.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_batch_insert_builder.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_account_data_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go
  services/horizon/internal/db2/history/mock_q_data.go
  services/horizon/internal/db2/history/mock_q_offers.go
  services/horizon/internal/db2/history/mock_q_trust_lines.go
  services/horizon/internal/db2/history/mock_trust_lines_batch_insert_builder.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/orderbook_test.go
  services/horizon/internal/db2/history/sequence_provider_test.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_batch_insert_builder.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/account_data_processor.go
  services/horizon/internal/expingest/processors/accounts_data_processor_test.go
  services/horizon/internal/expingest/processors/offers_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/processors/signer_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
  xdr/account_entry.go
  xdr/trust_line_entry.go
Labels: cla: yes

#2900 Update horizon-cmp for 1.7 release
  tools/horizon-cmp/internal/response.go
Labels: cla: yes

#2902 Rebuild XDRs to match RC.
  xdr/Stellar-ledger-entries.x
  xdr/Stellar-transaction.x
  xdr/xdr_generated.go
Labels: cla: yes

#2904 exp/ingest: Extend stats ledger transaction processor with Protocol 14 operations.
  exp/ingest/io/stats_ledger_transaction_processor.go
  exp/ingest/io/stats_ledger_transaction_processor_test.go
Labels: cla: yes

#2905 expingest: Add placeholder for new operations and verifier
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/verify.go
Labels: cla: yes

#2907 Merge horizon v1.7.0 back into master
  go.mod
  services/horizon/CHANGELOG.md
  services/horizon/cmd/version.go
  services/horizon/internal/actions/metrics.go
  services/horizon/internal/app.go
  services/horizon/internal/app_test.go
  services/horizon/internal/db2/history/trade.go
  services/horizon/internal/db2/history/trade_aggregation.go
  services/horizon/internal/db2/history/trade_aggregation_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/httpx/middleware.go
  services/horizon/internal/httpx/router.go
  services/horizon/internal/httpx/server.go
  services/horizon/internal/init.go
  services/horizon/internal/logmetrics/main.go
  services/horizon/internal/logmetrics/main_test.go
  services/horizon/internal/txsub/system.go
  services/horizon/internal/txsub/system_test.go
  support/time/main.go
  tools/horizon-cmp/internal/response.go
Labels: cla: yes

#2898 services/horizon/expingest: Add state and ledger processor for Claimable balances.
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
  services/horizon/internal/db2/history/claimable_balances_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_claimable_balances.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/39_claimable_balances.sql
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/claimable_balances_processor.go
  services/horizon/internal/expingest/processors/claimable_balances_processor_test.go
  xdr/claimable_balance_id.go
  xdr/db.go
  xdr/db_test.go
  xdr/ledger_entry.go
  xdr/ledger_key.go
Labels: cla: yes

#2897 services/horizon: Add sponsors ingestion to change processors
  exp/ingest/io/change.go
  exp/ingest/io/ledger_transaction_test.go
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/db2/history/account_data.go
  services/horizon/internal/db2/history/account_signers.go
  services/horizon/internal/db2/history/account_signers_batch_insert_builder.go
  services/horizon/internal/db2/history/account_signers_test.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_signers.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/sponsor.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/signer_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
  services/horizon/internal/test/scenarios/base-horizon.sql
  services/horizon/internal/test/scenarios/bindata.go
  xdr/account_entry.go
  xdr/account_entry_test.go
  xdr/ledger_entry.go
  xdr/ledger_entry_test.go
Labels: cla: yes

#2896 exp/services/captivecore/internal: Add HTTP server for managing a remote captive core instance
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/services/captivecore/internal/api.go
  exp/services/captivecore/internal/api_test.go
  exp/services/captivecore/internal/server.go
  exp/services/captivecore/internal/server_test.go
  exp/services/captivecore/main.go
Labels: cla: yes

#2909 exp/services/market-tracker: add sample config
  exp/services/market-tracker/config_sample.json
Labels: cla: yes

#2911 services/horizon/internal/expingest: Ingest CAP23 Operations details and participants.
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
  xdr/asset.go
  xdr/asset_test.go
Labels: cla: yes

#2919 Sponsored claimable services/horizon: Ingest sponsor while ingesting claimable balances.
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
  services/horizon/internal/db2/history/claimable_balances_test.go
  services/horizon/internal/db2/history/mock_q_claimable_balances.go
  services/horizon/internal/expingest/processors/claimable_balances_processor.go
  services/horizon/internal/expingest/processors/claimable_balances_processor_test.go
Labels: cla: yes

#2914 services/horizon/internal/expingest: Ingest CAP23 Operations effects.
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
Labels: cla: yes

#2910 services/horizon: Add `horizon ingest init-genesis-state` command
  services/horizon/cmd/ingest.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
Labels: cla: yes

#2923 horizon/internal/ingest:Add Claimable Balances to state verifier.
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/mock_q_claimable_balances.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  xdr/claimant.go
  xdr/claimant_test.go
Labels: cla: yes

#2925 services/horizon: (protocol 14) Fix various SponsoringID minor issues
  services/horizon/internal/db2/history/accounts_test.go
  services/horizon/internal/db2/history/sponsor.go
  services/horizon/internal/db2/history/trust_lines_test.go
  xdr/ledger_entry.go
  xdr/ledger_entry_test.go
Labels: cla: yes

#2927 services/horizon: Fix route query params for offers/:offer_id.
  services/horizon/internal/action_offers_test.go
  services/horizon/internal/httpx/router.go
Labels: bug, cla: yes

#2918 exp/services/captivecore/internal: Implement RemoteCaptiveCore HTTP client
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/history_archive_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/ledgerbackend/mock_database_backend.go
  exp/ingest/ledgerbackend/remote_captive_core.go
  exp/services/captivecore/internal/api.go
  exp/services/captivecore/internal/api_test.go
  exp/services/captivecore/internal/server_test.go
  services/horizon/cmd/db.go
  services/horizon/cmd/ingest.go
  services/horizon/cmd/root.go
  services/horizon/internal/config.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fake_ledger_backend.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2929 services/horizon: Create CHANGELOG entry for Horizon 1.7.1
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2930 services:horizon: Merge Horizon 1.7.1 back into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/action_offers_test.go
  services/horizon/internal/httpx/router.go
Labels: cla: yes

#2931 services/horizon/internal/db2/history: Remove hash id from claimable_balances schema
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/39_claimable_balances.sql
  services/horizon/internal/db2/schema/migrations/40_add_sponsor_to_state_tables.sql
  xdr/main.go
  xdr/main_test.go
Labels: cla: yes

#2921 services/horizon: Update state verify metrics
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2924 services/horizon: Add /claimable_balances/:id.
  protocols/horizon/main.go
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/claimable_balance_test.go
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/claimable_balances_test.go
  services/horizon/internal/httpx/router.go
  services/horizon/internal/resourceadapter/claimable_balances.go
  services/horizon/internal/resourceadapter/claimable_balances_test.go
Labels: cla: yes

#2916 services/horizon: Integration tests
  .circleci/config.yml
  go.list
  go.mod
  go.sum
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration.go
Labels: cla: yes

#2936 exp/ingest/io: Fix LedgerTransactionReader tx meta check
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_transaction_reader.go
Labels: cla: yes

#2922 services/horizon: Fix horizon_db_wait_duration_seconds_total metric
  services/horizon/internal/init.go
Labels: cla: yes

#2917 services/horizon: Update ops processor for CAP 33
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/expingest/processors/operations_processor.go
  services/horizon/internal/expingest/processors/operations_processor_test.go
  services/horizon/internal/expingest/processors/participants_processor.go
  services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
Labels: cla: yes

#2938 services/horizon: Add horizon_db_max_open_connections metric
  services/horizon/internal/app.go
  services/horizon/internal/init.go
Labels: cla: yes

#2937 services/horizon: Export horizon_build_info in /metrics
  services/horizon/internal/app.go
  services/horizon/internal/init.go
Labels: cla: yes

#2952 services/horizon: Update goautoneg dep to not use BitBucket repo.
  go.list
  go.mod
  go.sum
  services/horizon/internal/render/main.go
Labels: cla: yes

#2954 Fix publish_state_diff_docker_image Circle-CI job
  exp/tools/dump-ledger-state/Dockerfile
Labels: cla: yes

#2953 services/horizon: Run integration tests on each PR
  .circleci/config.yml
Labels: cla: yes

#2947 xdr: Add JSON representation for ClaimPredicate
  protocols/horizon/main.go
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
  services/horizon/internal/resourceadapter/claimable_balances.go
  services/horizon/internal/resourceadapter/claimable_balances_test.go
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#2955 horizonclient: use root error to check horizon error
  clients/horizonclient/error_helpers.go
  clients/horizonclient/error_helpers_test.go
Labels: cla: yes, horizonclient

#2956 services/horizon: Clone a DB session in System.initMetrics/GetExpStateInvalid
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#2945 services/horizon: Update state verifier with CAP33 support.
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
Labels: cla: yes

#2961 services/horizon: Add port specification to work on host network mode
  services/horizon/docker/docker-compose.yml
Labels: cla: yes

#2963 recoverysigner: set max db open conns to 20
  exp/services/recoverysigner/cmd/serve.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes, recoverysigner, vibrant

#2958 Fix server shutdown race
  services/horizon/internal/app.go
  services/horizon/internal/httpx/server.go
Labels: cla: yes

#2962 tools/horizon-cmp: Add routes coverage and misc fixes
  tools/horizon-cmp/init_routes.go
  tools/horizon-cmp/internal/response.go
  tools/horizon-cmp/internal/route_counter.go
  tools/horizon-cmp/internal/route_counter_test.go
  tools/horizon-cmp/main.go
Labels: cla: yes

#2964 services/horizon/internal/expingest: Exclude shutdown errors from logs in OrderBookStream
  services/horizon/internal/expingest/orderbook.go
Labels: cla: yes

#2966 Horizon 1.8.0 CHANGELOG
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2971 exp/services/captivecore: Add README for captivecore server
  exp/services/captivecore/README.md
Labels: cla: yes

#2972 services/horizon/docker: Comment-out STELLAR_CORE_BINARY_PATH
  services/horizon/docker/Dockerfile
Labels: cla: yes

#2974 Merge release-horizon-v1.8.0 into master
  services/horizon/CHANGELOG.md
  services/horizon/docker/Dockerfile
  services/horizon/internal/app.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/httpx/server.go
  tools/horizon-cmp/init_routes.go
  tools/horizon-cmp/internal/response.go
  tools/horizon-cmp/internal/route_counter.go
  tools/horizon-cmp/internal/route_counter_test.go
  tools/horizon-cmp/main.go
Labels: cla: yes
