Repository stellar/go, pull requests merged in 2020-02, with the labels that each got.

#2218 services/horizon/expingest: Fix Signers processor performace
  services/horizon/internal/expingest/processors/signer_processor_test.go
  services/horizon/internal/expingest/processors/signers_processor.go
Labels: cla: yes, horizon

#2216 keypair: add MustParseAddress, MustParseFull
  keypair/main.go
  keypair/main_test.go
Labels: cla: yes

#2215 txnbuild: ignore txhash (preauth) and xhash signers in sep-10
  txnbuild/transaction.go
  txnbuild/transaction_test.go
Labels: cla: yes

#2221 exp/ingest: Use errors.Wrap to propagate errors
  exp/ingest/adapters/history_archive_adapter.go
  exp/ingest/io/single_ledger_state_reader.go
Labels: cla: yes

#2220 services/horizon/internal/expingest: Refactor ingestion system to use explicit FSM
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
Labels: cla: yes

#2226 Revert "support/db: Support concurrent queries in a transaction (#2024)"
  services/horizon/internal/expingest/main_test.go
  support/db/main.go
  support/db/session.go
  support/db/session_test.go
Labels: cla: yes

#2229 clients/horizonclient: Add support for Accounts endpoint.
  clients/horizonclient/accounts_request.go
  clients/horizonclient/client.go
  clients/horizonclient/examples_test.go
  clients/horizonclient/main.go
  clients/horizonclient/main_test.go
  clients/horizonclient/mocks.go
  protocols/horizon/main.go
Labels: cla: yes

#2228 services/horizon: Update the usage message of `--max-path-length`
  services/horizon/cmd/root.go
Labels: cla: yes, horizon

#2230 client/horizonclient: Extend offers to support new filters.
  clients/horizonclient/examples_test.go
  clients/horizonclient/main.go
  clients/horizonclient/main_test.go
  clients/horizonclient/offer_request.go
Labels: cla: yes

#2238 Update readme.md
  services/horizon/internal/docs/reference/readme.md
Labels: cla: yes

#2240 services/horizon/internal/expingest: Remove reporter
  services/horizon/internal/expingest/reporter.go
Labels: cla: yes

#2236 services/horizon/internal/db2: Add batch insert builders for history_accounts and history_assets tables
  services/horizon/internal/db2/history/account.go
  services/horizon/internal/db2/history/account_test.go
  services/horizon/internal/db2/history/asset.go
  services/horizon/internal/db2/history/asset_test.go
  services/horizon/internal/db2/history/effect_batch_insert_builder_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_effects.go
  services/horizon/internal/db2/history/mock_q_participants.go
  services/horizon/internal/db2/history/mock_q_trades.go
  services/horizon/internal/db2/history/trade.go
  services/horizon/internal/db2/history/trade_test.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processors/effects_processor.go
  services/horizon/internal/expingest/processors/effects_processor_test.go
  services/horizon/internal/expingest/processors/participants_processor.go
  services/horizon/internal/expingest/processors/participants_processor_test.go
  services/horizon/internal/expingest/processors/trades_processor.go
  services/horizon/internal/expingest/processors/trades_processor_test.go
  support/db/batch_insert_builder.go
  support/db/batch_insert_builder_test.go
  support/db/internal_test.go
  support/db/main.go
Labels: cla: yes

#2243 exp/orderbook: Remove duffcopy'ies in `consumeOffers*` functions
  exp/orderbook/dfs.go
Labels: cla: yes, horizon

#2235 services/horizon: Fix `reingest range` command params
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
Labels: cla: yes, horizon

#2241 services/horizon/expingest: Wrap errors returned by processors
  services/horizon/internal/expingest/group_processors.go
Labels: cla: yes

#2227 tools/horizon-cmp: Add history mode
  tools/horizon-cmp/history.go
  tools/horizon-cmp/main.go
Labels: cla: yes, horizon

#2234 tools/horizon-cmp: Send two HTTP requests at the same time
  tools/horizon-cmp/main.go
Labels: cla: yes

#2244 support/http/httpdecode: add decoding of querys
  support/http/httpdecode/httpdecode.go
  support/http/httpdecode/httpdecode_test.go
Labels: cla: yes

#2242 services/horizon/internal/expingest: Allow horizon db reingest range to run concurrently with Horizon
  services/horizon/cmd/db.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
Labels: cla: yes

#2239 services/horizon/internal/expingest: Add expingest stress-test command
  services/horizon/cmd/ingest.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fake_ledger_backend.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/logger_change_reader_test.go
  services/horizon/internal/expingest/logger_state_reader.go
  services/horizon/internal/expingest/logger_state_reader_test.go
  services/horizon/internal/expingest/logging_change_reader.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processors_runner.go
  services/horizon/internal/expingest/stress_test.go
Labels: cla: yes

#2246 keypair: add SignBase64 that returns signatures strings
  keypair/from_address.go
  keypair/from_address_test.go
  keypair/full.go
  keypair/full_test.go
  keypair/main.go
Labels: cla: yes

#2252 services/horizon/internal: Support filtering offers by `buying` or `selling`.
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/query_params.go
  services/horizon/internal/actions/query_params_test.go
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/docs/reference/endpoints/offers.md
Labels: cla: yes

#2253 services/horizon/internal/docs: Update API docs for 1.0.0.
  services/horizon/internal/docs/reference/endpoints/accounts.md
  services/horizon/internal/docs/reference/endpoints/assets-all.md
  services/horizon/internal/docs/reference/endpoints/fee-stats.md
  services/horizon/internal/docs/reference/endpoints/offer-details.md
  services/horizon/internal/docs/reference/endpoints/offers-for-account.md
  services/horizon/internal/docs/reference/endpoints/offers.md
  services/horizon/internal/docs/reference/endpoints/path-finding-strict-send.md
  services/horizon/internal/docs/reference/resources/account.md
  services/horizon/internal/docs/reference/resources/effect.md
  services/horizon/internal/docs/reference/resources/offer.md
  services/horizon/internal/docs/reference/resources/operation.md
Labels: cla: yes

#2257 services/horizon/internal/docs: Improve more documentation.
  services/horizon/internal/docs/reference/resources/account.md
  services/horizon/internal/docs/reference/resources/ledger.md
  services/horizon/internal/docs/reference/resources/operation.md
  services/horizon/internal/docs/reference/resources/transaction.md
Labels: cla: yes

#2255 keypair: remove unnecessary cast
  keypair/full.go
Labels: cla: yes

#2256 services/horizon/internal/httpx: remove obsolete CloseNotifier code
  services/horizon/internal/httpx/request.go
  services/horizon/internal/middleware.go
Labels: cla: yes

#2245 support/http/httpdecode: add decoding of path params
  go.list
  go.mod
  go.sum
  support/http/httpdecode/httpdecode.go
  support/http/httpdecode/httpdecode_test.go
Labels: cla: yes

#2261 services/horizon: Move /metrics to internal server
  services/horizon/CHANGELOG.md
  services/horizon/cmd/root.go
  services/horizon/internal/app.go
  services/horizon/internal/config.go
  services/horizon/internal/docs/reference/endpoints/metrics.md
  services/horizon/internal/web.go
Labels: cla: yes

#2260 services/horizon: Add new ingestion system metrics to /metrics
  clients/horizonclient/main_test.go
  protocols/horizon/main.go
  services/horizon/internal/actions_metrics.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2265 services/horizon/actions: Add Prometheus text exposition format in /metrics
  services/horizon/internal/actions/base.go
  services/horizon/internal/actions/responders.go
  services/horizon/internal/actions_metrics.go
Labels: cla: yes, horizon

#2251 exp/ingest/io: Add StatsChangeProcessor
  exp/ingest/io/stats_change_processor.go
  exp/ingest/io/stats_change_processor_test.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processors_runner.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify_range_state_test.go
Labels: cla: yes

#2269 services/horizon: Fix misc /metrics issues
  protocols/horizon/main.go
  services/horizon/internal/actions_metrics.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/resourceadapter/root.go
Labels: cla: yes

#2270 /services/horizon: Fix stats return value in RunOrderBookProcessorOnLedger
  services/horizon/internal/expingest/processors_runner.go
Labels: cla: yes

#2259 services/horizon/internal: Add test for invalid buying/selling asset.
  services/horizon/internal/actions/query_params_test.go
Labels: cla: yes

#2266 services/horizon/internal/expingest: Add group processors test
  services/horizon/internal/expingest/group_processors_test.go
Labels: cla: yes

#2273 exp/ingest/io: Add StatsLedgerTransactionProcessor
  exp/ingest/io/stats_change_processor.go
  exp/ingest/io/stats_ledger_transaction_processor.go
  exp/ingest/io/stats_ledger_transaction_processor_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processors_runner.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify_range_state_test.go
Labels: cla: yes

#2277 services/horizon/txsub: Skip checking Core DB if Horizon is ingesting failed txs
  services/horizon/internal/init.go
  services/horizon/internal/txsub/results/db/main.go
  services/horizon/internal/txsub/results/db/main_test.go
Labels: cla: yes

#2279 txnbuild: remove superfluous signing key in challenge txn test
  txnbuild/transaction_test.go
Labels: cla: yes

#2278 exp/services/webauth: rename commands package to cmd
  exp/services/webauth/cmd/genjwtkey.go
  exp/services/webauth/cmd/serve.go
  exp/services/webauth/main.go
Labels: cla: yes

#2282 services/horizon/expingest: ProcessorRunner tests
  exp/orderbook/graph.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/mock_orderbook_graph.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/new_orderbook_processor.go
Labels: cla: yes

#2267 exp/services/recoverysigner: add service
  exp/services/recoverysigner/README.md
  exp/services/recoverysigner/cmd/serve.go
  exp/services/recoverysigner/internal/account/account.go
  exp/services/recoverysigner/internal/account/memory_store.go
  exp/services/recoverysigner/internal/account/store.go
  exp/services/recoverysigner/internal/serve/auth/claims.go
  exp/services/recoverysigner/internal/serve/auth/firebase.go
  exp/services/recoverysigner/internal/serve/auth/firebase_test.go
  exp/services/recoverysigner/internal/serve/auth/sep10.go
  exp/services/recoverysigner/internal/serve/auth/sep10_test.go
  exp/services/recoverysigner/internal/serve/errors.go
  exp/services/recoverysigner/internal/serve/errors_test.go
  exp/services/recoverysigner/internal/serve/serve.go
  exp/services/recoverysigner/main.go
  go.list
  go.mod
  go.sum
  support/http/httpauthz/httpauthz.go
  support/http/httpauthz/httpauthz_test.go
Labels: cla: yes

#2285 services/horizon: Change INTERNAL_PORT to ADMIN_PORT
  services/horizon/CHANGELOG.md
  services/horizon/cmd/root.go
  services/horizon/internal/app.go
  services/horizon/internal/config.go
  services/horizon/internal/docs/reference/endpoints/metrics.md
Labels: cla: yes

#2286 tools/horizon-cmp: Retry on Latest-Ledger header mismatch
  tools/horizon-cmp/internal/response.go
  tools/horizon-cmp/main.go
Labels: cla: yes

#2287 services/horizon/txsub: Use CoreDB for SequenceProvider
  services/horizon/internal/init.go
  services/horizon/internal/txsub/results/db/main.go
  services/horizon/internal/txsub/results/db/main_test.go
Labels: cla: yes

#2289 services/horizon: Change default of max-path-length to 3
  services/horizon/cmd/root.go
Labels: cla: yes

#2274 exp/services/recoverysigner: add account registration endpoint
  exp/services/recoverysigner/internal/serve/account_post.go
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_response.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2275 exp/services/recoverysigner: add account list endpoint
  exp/services/recoverysigner/internal/account/memory_store.go
  exp/services/recoverysigner/internal/serve/account_list.go
  exp/services/recoverysigner/internal/serve/account_list_test.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2276 exp/services/recoverysigner: add sign endpoint
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2291 exp/services/recoverysigner: rename auth.Claims to auth.Auth
  exp/services/recoverysigner/internal/serve/account_list_test.go
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
  exp/services/recoverysigner/internal/serve/auth/auth.go
  exp/services/recoverysigner/internal/serve/auth/claims.go
  exp/services/recoverysigner/internal/serve/auth/firebase.go
  exp/services/recoverysigner/internal/serve/auth/firebase_test.go
  exp/services/recoverysigner/internal/serve/auth/sep10.go
  exp/services/recoverysigner/internal/serve/auth/sep10_test.go
Labels: cla: yes

#2292 exp/services/recoverysigner: setup firebase auth client only once
  exp/services/recoverysigner/internal/serve/auth/firebase.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2290 Backfill fee stats data to make the client compatible with horizon 1.X and 0.X.
  clients/horizonclient/client.go
  clients/horizonclient/main_test.go
Labels: cla: yes

#2294 keypair: add unmarshal and marshal functions to FromAddress
  keypair/from_address.go
  keypair/from_address_test.go
Labels: cla: yes

#2297 exp/services/recoverysigner: add Dockerfile
  Makefile
  exp/services/recoverysigner/Makefile
  exp/services/recoverysigner/docker/Dockerfile
Labels: cla: yes

#2296 exp/services/webauth: add Dockerfile
  Makefile
  exp/services/webauth/Makefile
  exp/services/webauth/docker/Dockerfile
Labels: cla: yes

#2298 exp/ingest: Polish interfaces
  exp/ingest/adapters/history_archive_adapter.go
  exp/ingest/adapters/history_archive_adapter_test.go
  exp/ingest/adapters/mocks.go
  exp/ingest/io/archive_ledger_reader.go
  exp/ingest/io/change.go
  exp/ingest/io/change_reader.go
  exp/ingest/io/errors.go
  exp/ingest/io/genesis_ledger_state_reader.go
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_reader.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/main.go
  exp/ingest/io/memory_temp_set.go
  exp/ingest/io/memory_temp_set_test.go
  exp/ingest/io/mock_change_reader.go
  exp/ingest/io/mock_ledger_writer.go
  exp/ingest/io/mock_state_reader.go
  exp/ingest/io/mock_state_writer.go
  exp/ingest/io/postgres_temp_set.go
  exp/ingest/io/processors.go
  exp/ingest/io/single_ledger_state_reader.go
  exp/ingest/io/single_ledger_state_reader_test.go
  exp/ingest/verify/main.go
  exp/ingest/verify/main_test.go
  services/horizon/internal/expingest/logger_change_reader_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/verify.go
  tools/archive-reader/archive_reader.go
Labels: cla: yes

#2295 exp/services/recoverysigner: validate account address in urls
  exp/services/recoverysigner/internal/serve/account_post.go
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
Labels: cla: yes

#2302 keypair: add check that FromAddress implements encoding.Unmarshaler
  keypair/from_address.go
Labels: cla: yes

#2300 protocols/horizon: Make offerBase an inline struct and move back original fields to Offer.
  protocols/horizon/main.go
Labels: cla: yes

#2301 services/horizon: Fix docker-compose Postgres' auth
  services/horizon/docker/docker-compose.yml
Labels: cla: yes

#2299 services/horizon/expingest: Ingest into memory only flag
  services/horizon/cmd/root.go
  services/horizon/internal/config.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2306 services/horizon: Check for --history-archive-urls flag when --ingest set
  services/horizon/cmd/root.go
Labels: cla: yes

#2303 clients/horizon: Extend client with Offer details support
  clients/horizonclient/client.go
  clients/horizonclient/examples_test.go
  clients/horizonclient/main.go
  clients/horizonclient/main_test.go
  clients/horizonclient/mocks.go
  clients/horizonclient/offer_request.go
  clients/horizonclient/offer_request_test.go
Labels: cla: yes

#2309 exp/tools/dump-ledger-state: Rewrite dump ledger state job to use new ingestion design
  exp/tools/dump-ledger-state/main.go
Labels: cla: yes

#2312 exp/services/webauth: fix the horizon timeout
  exp/services/webauth/internal/serve/serve.go
Labels: cla: yes

#2313 exp/services/recoverysigner: fix the horizon timeout
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2308 clients/horizon: 2.1.0 CHANGELOG
  clients/horizonclient/CHANGELOG.md
Labels: cla: yes

#2318 Update Client and date.
  clients/horizonclient/CHANGELOG.md
  clients/horizonclient/main_test.go
  clients/horizonclient/version.go
Labels: cla: yes

#2317 Horizon v1.0.0 CHANGELOG
  services/horizon/CHANGELOG.md
  services/horizon/internal/docs/admin.md
Labels: cla: yes

#2314 support/http: allow services to specify the logger used by the logging middleware
  exp/services/recoverysigner/internal/serve/serve.go
  exp/services/webauth/internal/serve/serve.go
  services/bridge/main.go
  services/compliance/main.go
  services/federation/main.go
  services/friendbot/main.go
  support/http/logging_middleware.go
  support/http/logging_middleware_test.go
  support/http/mux.go
  support/render/health/example_test.go
Labels: cla: yes

#2319 services/ticker add stripped down ticker Dockerfile
  Makefile
  services/ticker/Makefile
  services/ticker/README.md
  services/ticker/docker/Dockerfile
  services/ticker/docker/Dockerfile-dev
Labels: cla: yes

#2305 support/db/dbtest: Remove postgresql-client-9.6 dependency for running tests
  .circleci/config.yml
  services/horizon/internal/actions_operation_test.go
  services/horizon/internal/simplepath/order_book_test.go
  services/horizon/internal/test/load_scenario.go
  services/horizon/internal/test/main.go
  services/horizon/internal/test/scenarios/account_merge-core.sql
  services/horizon/internal/test/scenarios/allow_trust-core.sql
  services/horizon/internal/test/scenarios/asset_stat_account-core.sql
  services/horizon/internal/test/scenarios/asset_stat_operations-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_1-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_2-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_3-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_4-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_5-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_6-core.sql
  services/horizon/internal/test/scenarios/asset_stat_trustlines_7-core.sql
  services/horizon/internal/test/scenarios/bad_cost-core.sql
  services/horizon/internal/test/scenarios/bad_cost-horizon.sql
  services/horizon/internal/test/scenarios/base-core.sql
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/change_trust-core.sql
  services/horizon/internal/test/scenarios/failed_transactions-core.sql
  services/horizon/internal/test/scenarios/ingest_asset_stats-core.sql
  services/horizon/internal/test/scenarios/kahuna-2-core.sql
  services/horizon/internal/test/scenarios/kahuna-core.sql
  services/horizon/internal/test/scenarios/main.go
  services/horizon/internal/test/scenarios/non_native_payment-core.sql
  services/horizon/internal/test/scenarios/offer_ids-core.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_1-core.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_2-core.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_3-core.sql
  services/horizon/internal/test/scenarios/order_books-core.sql
  services/horizon/internal/test/scenarios/order_books_310-core.sql
  services/horizon/internal/test/scenarios/pathed_payment-core.sql
  services/horizon/internal/test/scenarios/paths-core.sql
  services/horizon/internal/test/scenarios/paths_strict_send-core.sql
  services/horizon/internal/test/scenarios/self_send-core.sql
  services/horizon/internal/test/scenarios/send_to_issuer-core.sql
  services/horizon/internal/test/scenarios/set_options-core.sql
  services/horizon/internal/test/scenarios/trades-core.sql
  services/horizon/internal/test/t.go
  support/db/dbtest/db.go
  support/db/dbtest/main.go
  support/db/dbtest/postgres.go
  support/db/dbtest/postgres_test.go
Labels: cla: yes

#2321 tools/horizon-cmp: Document horizon-cmp history.
  tools/horizon-cmp/README.md
Labels: cla: yes

#2316 services/horizon: expose date header
  services/horizon/internal/web.go
Labels: cla: yes

#2328 services/ticker: handle invalid TOML urls gracefully
  services/ticker/internal/scraper/asset_scraper.go
  services/ticker/internal/scraper/asset_scraper_test.go
Labels: cla: yes, ticker

#2323 exp/services/recoverysigner: remove type, add identities
  exp/services/recoverysigner/internal/account/account.go
  exp/services/recoverysigner/internal/account/account_test.go
  exp/services/recoverysigner/internal/serve/account_list.go
  exp/services/recoverysigner/internal/serve/account_list_test.go
  exp/services/recoverysigner/internal/serve/account_post.go
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_response.go
Labels: cla: yes

#2330 horizonclient: add GetError func for retrieving a horizon error
  clients/horizonclient/error_helpers.go
  clients/horizonclient/error_helpers_test.go
Labels: cla: yes

#2332 exp/services/recoverysigner: rename public_key to signer
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
Labels: cla: yes

#2325 all: add Go 1.14, deprecate Go 1.12
  .circleci/config.yml
  DEVELOPING.md
  Dockerfile
  README.md
  clients/horizonclient/README.md
  go.mod
  services/horizon/internal/docs/admin.md
  services/horizon/internal/docs/developing.md
  services/ticker/docker/Dockerfile-dev
  services/ticker/internal/scraper/asset_scraper_test.go
  staticcheck.sh
  txnbuild/README.md
Labels: cla: yes

#2337 exp/services/recoverysigner: add form url-encoded tests
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
Labels: cla: yes

#2336 Fix horizon db reap command
  services/horizon/CHANGELOG.md
  services/horizon/cmd/db.go
  services/horizon/internal/reap/main.go
  services/horizon/internal/reap/system.go
Labels: cla: yes

#2346 doc: update changelogs with drop of Go 1.12 support
  clients/horizonclient/CHANGELOG.md
  services/bridge/CHANGELOG.md
  services/compliance/CHANGELOG.md
  services/federation/CHANGELOG.md
  services/horizon/CHANGELOG.md
  services/keystore/CHANGELOG.md
  services/ticker/CHANGELOG.md
  tools/stellar-archivist/CHANGELOG.md
  tools/stellar-hd-wallet/CHANGELOG.md
  tools/stellar-sign/CHANGELOG.md
  tools/stellar-vanity-gen/CHANGELOG.md
  txnbuild/CHANGELOG.md
Labels: cla: yes

#2310 clients/horizonclient: fix inconsistent units of time in HorizonTimeOut
  clients/horizonclient/CHANGELOG.md
  clients/horizonclient/client.go
  clients/horizonclient/examples_test.go
  clients/horizonclient/main.go
  exp/services/recoverysigner/internal/serve/serve.go
  exp/services/webauth/internal/serve/serve.go
Labels: cla: yes, horizonclient
