Repository stellar/go, pull requests merged in 2020-06, with the labels that each got.

#2630 services/horizon: Update in memory orderbook graph using Horizon DB instead of ingestion
  exp/orderbook/graph.go
  services/horizon/CHANGELOG.md
  services/horizon/cmd/root.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/app.go
  services/horizon/internal/config.go
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/db2/history/key_value.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_offers.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_batch_insert_builder.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/orderbook.go
  services/horizon/internal/db2/history/orderbook_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/36_add_orderbook_index.sql
  services/horizon/internal/db2/schema/migrations/36_deleted_offers.sql
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/mock_orderbook_graph.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/offers_processor.go
  services/horizon/internal/expingest/processors/offers_processor_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/init.go
  services/horizon/internal/web.go
  xdr/db.go
Labels: cla: yes

#2636 support/render/problem: fix 500 detail message
  support/render/problem/problem.go
Labels: cla: yes

#2640 txnbuild: Make txnbuild create V1 transactions
  clients/horizonclient/examples_test.go
  clients/horizonclient/main_test.go
  exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
  exp/services/webauth/internal/serve/challenge_test.go
  services/friendbot/internal/friendbot_test.go
  txnbuild/CHANGELOG.md
  txnbuild/change_trust_test.go
  txnbuild/example_test.go
  txnbuild/fee_bump_test.go
  txnbuild/helpers_test.go
  txnbuild/signers_test.go
  txnbuild/transaction.go
  txnbuild/transaction_fee_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#2637 services/ticker: reduce the ticker query test to raw request response comparisons
  services/ticker/internal/graphql_test.go
Labels: cla: yes

#2639 services/horizon/internal/expingest: Remove orderbook graph from ingestion system
  services/horizon/cmd/ingest.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/new_orderbook_processor.go
  services/horizon/internal/expingest/processors/orderbook_processor_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2642 Merge master into 1.4.0 release branch
  services/horizon/cmd/ingest.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/new_orderbook_processor.go
  services/horizon/internal/expingest/processors/orderbook_processor_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/init.go
  support/render/problem/problem.go
Labels: cla: yes

#2649 exp/orderbook: Allow updates to the order book graph which span multiple ledgers
  exp/orderbook/batch.go
  exp/orderbook/graph_test.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2652 services/horizon: Clone DB session for each history endpoint request
  services/horizon/internal/handler.go
  services/horizon/internal/middleware.go
  services/horizon/internal/stream_handler_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#2646 Update prototype to run captive on online ingestion mode.
  services/horizon/internal/init.go
Labels: cla: yes

#2653 services/horizon/internal: Include request context when cloning session for request
  services/horizon/internal/middleware.go
Labels: cla: yes

#2638 exp/services/recoverysigner: remove signer field from sign with signing address response
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
Labels: cla: yes

#2647 exp/services/recoverysigner: support multiple sep10 json web keys in the key set
  exp/services/recoverysigner/internal/serve/auth/sep10.go
  exp/services/recoverysigner/internal/serve/auth/sep10_test.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2656 services/horizon/internal/db2/schema: Remove deleted offers before droping deleted column
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/36_deleted_offers.sql
Labels: cla: yes

#2650 txnbuild: Allow fee bump transactions to bump v0 transactions
  txnbuild/fee_bump_test.go
  txnbuild/transaction.go
Labels: cla: yes

#2651 txnbuild: Add ToXDR functions which do not return errors
  txnbuild/CHANGELOG.md
  txnbuild/signers_test.go
  txnbuild/transaction.go
Labels: cla: yes

#2658 services/horizon/internal/expingest: Fix OrderBookStream verification
  services/horizon/internal/expingest/orderbook.go
  services/horizon/internal/expingest/orderbook_test.go
Labels: cla: yes

#2657 exp/ingest/io: Cache the latest fetched ledger in captiveStellarCore
  exp/ingest/ledgerbackend/captive_core_backend.go
Labels: cla: yes

#2662 services/horizon/internal/db2/history: Add AssetsForAddress.
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
Labels: cla: yes

#2663 services/horizon/internal/simplepath: Remove DB path finder.
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/simplepath/doc.go
  services/horizon/internal/simplepath/finder.go
  services/horizon/internal/simplepath/finder_test.go
  services/horizon/internal/simplepath/helpers_test.go
  services/horizon/internal/simplepath/order_book.go
  services/horizon/internal/simplepath/order_book_test.go
  services/horizon/internal/simplepath/path.go
  services/horizon/internal/simplepath/search.go
Labels: cla: yes

#2634 services/horizon: Gracefully handle incorrect assets in `GET /offers`
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions/query_params.go
  services/horizon/internal/actions/query_params_test.go
  xdr/asset.go
Labels: cla: yes

#2661 support/render/problem: Log request errors
  support/render/problem/default.go
  support/render/problem/problem.go
  support/render/problem/problem_test.go
Labels: cla: yes

#2668 services/horizon/docker/verify-range: Update base branch for verify range job
  services/horizon/docker/verify-range/start
Labels: cla: yes

#2672 services/horizon: Write captive-core logs to /dev/null when discarding them
  exp/ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#2671 services/horizon: Add missing Core dependencies in Dockefile
  services/horizon/docker/Dockerfile
Labels: cla: yes

#2665 exp/services/recoverysigner: fix the usage text
  exp/services/recoverysigner/README.md
  exp/services/recoverysigner/cmd/serve.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes

#2666 exp/services/webauth: remove old convjwt2jwk command
  exp/services/webauth/README.md
  exp/services/webauth/cmd/convjwt2jwk.go
  exp/services/webauth/main.go
  exp/support/jwtkey/jwtkey.go
  exp/support/jwtkey/jwtkey_test.go
Labels: cla: yes

#2675 services/horizon/interal/actions: Drop db2/core dependency in path finding actions.
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/db2/history/trust_lines_test.go
  services/horizon/internal/paths/mock_finder.go
  services/horizon/internal/web.go
Labels: cla: yes

#2677 services/horizon: Remove Core DB access from web, actions, and resourceadapters.
  services/horizon/internal/action.go
  services/horizon/internal/action_test.go
  services/horizon/internal/app.go
  services/horizon/internal/resourceadapter/account_entry.go
  services/horizon/internal/resourceadapter/account_flags.go
  services/horizon/internal/resourceadapter/account_thresholds.go
  services/horizon/internal/resourceadapter/balance.go
  services/horizon/internal/resourceadapter/balance_test.go
  services/horizon/internal/resourceadapter/signer.go
  services/horizon/internal/web.go
Labels: cla: yes

#2681 Update Horizon Changelog
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2645 exp/services/recoverysigner: add signing keys migration
  exp/services/recoverysigner/cmd/db_test.go
  exp/services/recoverysigner/internal/db/db_audit_test.go
  exp/services/recoverysigner/internal/db/dbmigrate/dbmigrate_generated.go
  exp/services/recoverysigner/internal/db/dbmigrate/dbmigrate_test.go
  exp/services/recoverysigner/internal/db/dbmigrate/migrations/20200603000000-create-signers.sql
  exp/services/recoverysigner/internal/db/dbmigrate/migrations/20200603000001-create-signers-audit.sql
Labels: cla: yes

#2667 exp/services/webauth: support multiple signing keys
  exp/services/webauth/README.md
  exp/services/webauth/cmd/serve.go
  exp/services/webauth/internal/serve/challenge.go
  exp/services/webauth/internal/serve/serve.go
  exp/services/webauth/internal/serve/token.go
  exp/services/webauth/internal/serve/token_test.go
Labels: cla: yes

#2678 exp/services/recoverysigner: remove accounts/{address}/sign endpoint
  exp/services/recoverysigner/README.md
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_test.go
Labels: cla: yes

#2680 exp/services/recoverysigner: remove signer response field
  exp/services/recoverysigner/internal/serve/account_delete.go
  exp/services/recoverysigner/internal/serve/account_delete_test.go
  exp/services/recoverysigner/internal/serve/account_get.go
  exp/services/recoverysigner/internal/serve/account_get_test.go
  exp/services/recoverysigner/internal/serve/account_list.go
  exp/services/recoverysigner/internal/serve/account_list_test.go
  exp/services/recoverysigner/internal/serve/account_post.go
  exp/services/recoverysigner/internal/serve/account_post_test.go
  exp/services/recoverysigner/internal/serve/account_put.go
  exp/services/recoverysigner/internal/serve/account_put_test.go
  exp/services/recoverysigner/internal/serve/account_response.go
Labels: cla: yes

#2679 exp/services/recoverysigner: update usage in readme
  exp/services/recoverysigner/README.md
Labels: cla: yes

#2685 support/http: log the route matched by the route handler
  support/http/logging_middleware.go
  support/http/logging_middleware_test.go
Labels: cla: yes

#2644 exp/ingest/io: Refactor readers
  exp/ingest/io/change.go
  exp/ingest/io/change_reader.go
  exp/ingest/io/ledger_change_reader.go
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_reader.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/ledger_transaction_reader.go
  exp/ingest/io/mock_ledger_reader.go
  exp/ingest/io/mock_ledger_transaction_processor.go
  exp/ingest/io/processors.go
  services/horizon/internal/expingest/processor_runner.go
Labels: cla: yes

#2691 services/horizon/internal/tests: Remove unemployed scenarios.
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/paths-core.sql
  services/horizon/internal/test/scenarios/paths-horizon.sql
  services/horizon/internal/test/scenarios/paths.rb
Labels: cla: yes

#2693 services/horizon: Add read-ahead buffer for decoded LedgerCloseMeta
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
Labels: cla: yes

#2690 services/horizon: Add transaction set operation count to history_ledger.
  protocols/horizon/main.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions/account_test.go
  services/horizon/internal/actions/offer_test.go
  services/horizon/internal/actions_account_test.go
  services/horizon/internal/actions_data_test.go
  services/horizon/internal/actions_ledger_test.go
  services/horizon/internal/db2/history/ledger.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_ledgers.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/37_add_tx_set_operation_count_to_ledgers.sql
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/expingest/processors/ledgers_processor.go
  services/horizon/internal/expingest/processors/ledgers_processor_test.go
  services/horizon/internal/middleware_test.go
  services/horizon/internal/resourceadapter/ledger.go
  services/horizon/internal/test/scenarios/base-horizon.sql
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/failed_transactions-horizon.sql
  services/horizon/internal/test/scenarios/kahuna-horizon.sql
  services/horizon/internal/test/scenarios/pathed_payment-horizon.sql
  services/horizon/internal/test/scenarios/paths_strict_send-horizon.sql
  services/horizon/internal/test/scenarios/trades-horizon.sql
Labels: cla: yes

#2695 Merge Captive core into 1.5.0 release branch
  exp/ingest/io/change.go
  exp/ingest/io/change_reader.go
  exp/ingest/io/ledger_change_reader.go
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_reader.go
  exp/ingest/io/ledger_transaction.go
  exp/ingest/io/ledger_transaction_reader.go
  exp/ingest/io/mock_ledger_reader.go
  exp/ingest/io/mock_ledger_transaction_processor.go
  exp/ingest/io/processors.go
  exp/ingest/io/single_ledger_state_reader_test.go
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/captive_core_backend_test.go
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/ledgerbackend/mock_database_backend.go
  exp/ingest/ledgerbackend/stellar_core_runner.go
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
  go.list
  go.mod
  go.sum
  services/horizon/cmd/db.go
  services/horizon/cmd/ingest.go
  services/horizon/cmd/root.go
  services/horizon/docker/Dockerfile
  services/horizon/internal/config.go
  services/horizon/internal/expingest/fake_ledger_backend.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processor_runner.go
  support/historyarchive/verify.go
  support/historyarchive/xdrstream.go
  support/historyarchive/xdrstream_test.go
  xdr/main.go
Labels: cla: yes

#2696 all: require at least v0.3.3 of golang.org/x/text
  go.list
  go.mod
  go.sum
Labels: cla: yes

#2697 exp/ingest/ledgerbackend: Cache LedgerCloseMeta in captiveStellarCore
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/captive_core_backend_test.go
Labels: cla: yes

#2699 services/horizon/internal/expingest: Fix logging in OrderBookStream
  services/horizon/internal/expingest/orderbook.go
Labels: cla: yes

#2700 services/horizon: Make verify-range's base branch configurable (defaulting to 1.4)
  services/horizon/docker/verify-range/start
Labels: cla: yes

#2701 Avoid dumping tx_meta in verify-range until we order it
  services/horizon/docker/verify-range/start
Labels: cla: yes

#2694 exp/ingest/ledgerbackend: Captive Core: Online mode
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/captive_core_backend_test.go
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/ledgerbackend/mock_database_backend.go
  exp/ingest/ledgerbackend/stellar_core_runner.go
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/resume_state_test.go
Labels: cla: yes

#2702 services/horizon: Remove ingest failed transactions flag
  services/horizon/CHANGELOG.md
  services/horizon/cmd/db.go
  services/horizon/cmd/ingest.go
  services/horizon/cmd/root.go
  services/horizon/internal/action_test.go
  services/horizon/internal/actions/operation.go
  services/horizon/internal/actions/operation_test.go
  services/horizon/internal/actions_operation_fee_stats.go
  services/horizon/internal/app.go
  services/horizon/internal/config.go
  services/horizon/internal/db2/core/account.go
  services/horizon/internal/db2/core/account_data.go
  services/horizon/internal/db2/core/ledger_header.go
  services/horizon/internal/db2/core/main.go
  services/horizon/internal/db2/core/main_test.go
  services/horizon/internal/db2/core/offer.go
  services/horizon/internal/db2/core/offer_test.go
  services/horizon/internal/db2/core/signer.go
  services/horizon/internal/db2/core/transaction.go
  services/horizon/internal/db2/core/transaction_fee.go
  services/horizon/internal/db2/core/transaction_fee_test.go
  services/horizon/internal/db2/core/transaction_test.go
  services/horizon/internal/db2/core/trustline.go
  services/horizon/internal/db2/core/trustline_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  services/horizon/internal/handler.go
  services/horizon/internal/helpers_test.go
  services/horizon/internal/init.go
  services/horizon/internal/txsub/results/db/main.go
  services/horizon/internal/txsub/results/db/main_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#2716 txnbuild: Update 3.2.0 release changelog
  txnbuild/CHANGELOG.md
Labels: cla: yes

#2710 exp/ingest/io: Replace ledgerbackend.LedgerCloseMeta with xdr.LedgerCloseMeta
  exp/ingest/io/ledger_change_reader.go
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_transaction_reader.go
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/ledger_backend.go
  exp/ingest/ledgerbackend/mock_database_backend.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fake_ledger_backend.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/processor_runner.go
  services/horizon/internal/expingest/processor_runner_test.go
  xdr/ledger_close_meta.go
  xdr/ledger_close_meta_test.go
Labels: cla: yes

#2720 exp/ingest/io: Fix bug in LedgerTransactionReader
  exp/ingest/io/ledger_change_reader.go
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_transaction_reader.go
  services/horizon/internal/expingest/processor_runner.go
Labels: cla: yes

#2723 exp/ingest/io: Check TxMeta version in LedgerTransactionReader
  exp/ingest/io/ledger_change_reader_test.go
  exp/ingest/io/ledger_transaction_reader.go
  exp/ingest/ledgerbackend/database_backend.go
Labels: cla: yes

#2717 services/horizon: Fix /metrics end-point.
  services/horizon/internal/app.go
  services/horizon/internal/app_test.go
Labels: cla: yes

#2692 exp/services/recoverysigner: add tink integration setup
  exp/services/recoverysigner/cmd/serve.go
  exp/services/recoverysigner/internal/crypto/crypto.go
  exp/services/recoverysigner/internal/crypto/crypto_test.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_insecure.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_insecure_test.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_secure.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_secure_test.go
  exp/services/recoverysigner/internal/crypto/keygen_test.go
  exp/services/recoverysigner/internal/crypto/mock_test.go
  exp/services/recoverysigner/internal/serve/serve.go
  go.list
  go.mod
  go.sum
Labels: cla: yes

#2648 Minor captive-core refactorings
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
Labels: cla: yes

#2726 services/horizon/internal: Load Core Latest Ledger from core's http info end-point.
  services/horizon/internal/actions_root_test.go
  services/horizon/internal/app.go
  services/horizon/internal/app_test.go
  services/horizon/internal/httpt_test.go
Labels: cla: yes

#2709 exp/ingest/ledgerbackend: HistoryArchiveBackend
  exp/ingest/ledgerbackend/history_archive_backend.go
  exp/ingest/ledgerbackend/history_archive_backend_test.go
Labels: cla: yes, ingest

#2736 services/horizon/internal/docs: Document tx_set_operation_count.
  services/horizon/internal/docs/reference/endpoints/ledgers-all.md
  services/horizon/internal/docs/reference/endpoints/ledgers-single.md
  services/horizon/internal/docs/reference/resources/ledger.md
Labels: cla: yes

#2729 exp/services/recoverysigner: add "encryption-tink-keyset create" cmd
  exp/services/recoverysigner/cmd/keyset.go
  exp/services/recoverysigner/cmd/keyset_test.go
Labels: cla: yes

#2739 services/horizon/docker/verify-range: Use S3 domain in verify-range
  services/horizon/docker/verify-range/stellar-core.cfg
Labels: cla: yes

#2741 exp/ingest/ledgerbackend: Fix data race in stellar_core_runner.
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
Labels: cla: yes

#2740 exp/services/recoverysigner: add encryption-tink-keyset rotate cmd
  exp/services/recoverysigner/cmd/keyset.go
  exp/services/recoverysigner/cmd/keyset_test.go
  exp/services/recoverysigner/main.go
Labels: cla: yes

#2743 services/horizon: Get historyQ from request, making sure that we use a clone of db.Session.
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
  services/horizon/internal/web.go
Labels: cla: yes

#2745 services/horizon/internal: Fix data race in root endpoint
  services/horizon/internal/actions_root.go
  services/horizon/internal/app.go
Labels: cla: yes

#2742 exp/ingest/ledgerbackend: Fix ordering of transaction envelopes in TxSet
  exp/ingest/ledgerbackend/database_backend.go
  exp/ingest/ledgerbackend/hash_order_test.go
  services/horizon/internal/expingest/database_backend_test.go
  services/horizon/internal/expingest/main.go
Labels: cla: yes

#2749 services/horizon/internal/actions: Don't setup repeatable read transaction in paths request.
  services/horizon/internal/actions_path.go
  services/horizon/internal/actions_path_test.go
Labels: cla: yes

#2748 exp/services/recoverysigner: add db usage to readme
  exp/services/recoverysigner/README.md
Labels: cla: yes, vibrant

#2744 exp/services/recoverysigner: add tests for starting with a rotated keyset
  exp/services/recoverysigner/internal/crypto/crypto_test.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_insecure_test.go
  exp/services/recoverysigner/internal/crypto/encrypterdecrypter_secure_test.go
  exp/services/recoverysigner/internal/crypto/keygen_test.go
Labels: cla: yes, vibrant

#2746 exp/services/recoverysigner: add encrypt and decrypt commands
  exp/services/recoverysigner/README.md
  exp/services/recoverysigner/cmd/keyset.go
  exp/services/recoverysigner/cmd/keyset_test.go
  exp/services/recoverysigner/cmd/serve.go
Labels: cla: yes, vibrant

#2600 services/horizon: Move effects endpoints to new actions code
  protocols/horizon/main.go
  services/horizon/internal/action.go
  services/horizon/internal/actions.go
  services/horizon/internal/actions/effects.go
  services/horizon/internal/actions/effects_test.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/operation.go
  services/horizon/internal/actions/operation_test.go
  services/horizon/internal/actions/validators.go
  services/horizon/internal/actions_effects.go
  services/horizon/internal/actions_operation_test.go
  services/horizon/internal/actions_payment_test.go
  services/horizon/internal/handler.go
  services/horizon/internal/helpers.go
  services/horizon/internal/urlparams.go
  services/horizon/internal/web.go
Labels: cla: yes

#2751 docs: fix word typo in comment.
  xdr/transaction_envelope.go
Labels: cla: yes

#2735 Update Changelog for Horizon v1.5.0.
  services/horizon/CHANGELOG.md
Labels: cla: yes

#2754 services/horizon/internal: Fix captive core runner for windows.
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/stellar_core_runner.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
Labels: cla: yes

#2755 Run build_packages in tests step.
  .circleci/config.yml
  services/keystore/README.md
  tools/archive-reader/CHANGELOG.md
  tools/archive-reader/README.md
Labels: cla: yes

#2758 exp/ingest/ledgerbackend: Update HistoryArchiveBackend to use updated LedgerBackend interface
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/history_archive_backend.go
  exp/ingest/ledgerbackend/history_archive_backend_test.go
  exp/ingest/ledgerbackend/ledger_backend.go
Labels: cla: yes

#2724 services/horizon: Parallelize `db reingest range`
  services/horizon/CHANGELOG.md
  services/horizon/cmd/db.go
  services/horizon/internal/app.go
  services/horizon/internal/expingest/build_state_test.go
  services/horizon/internal/expingest/db_integration_test.go
  services/horizon/internal/expingest/fsm.go
  services/horizon/internal/expingest/ingest_history_range_state_test.go
  services/horizon/internal/expingest/init_state_test.go
  services/horizon/internal/expingest/main.go
  services/horizon/internal/expingest/main_test.go
  services/horizon/internal/expingest/parallel.go
  services/horizon/internal/expingest/parallel_test.go
  services/horizon/internal/expingest/resume_state_test.go
  services/horizon/internal/expingest/stress_test.go
  services/horizon/internal/expingest/verify.go
  services/horizon/internal/expingest/verify_range_state_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2747 exp/ingest/ledgerbackend: Add helper functions to create and run subprocesses
  exp/ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#2764 exp/ingest/ledgerbackend: Fix getting ledgers before the first checkpoint in CaptiveStellarCore
  exp/ingest/ledgerbackend/captive_core_backend.go
  exp/ingest/ledgerbackend/captive_core_backend_test.go
  services/horizon/internal/expingest/fsm.go
Labels: cla: yes

#2759 services/horizon: Remove db2/core.
  services/horizon/CHANGELOG.md
  services/horizon/cmd/root.go
  services/horizon/internal/app.go
  services/horizon/internal/config.go
  services/horizon/internal/db2/core/main.go
  services/horizon/internal/db2/core/main_test.go
  services/horizon/internal/docs/reference/endpoints/metrics.md
  services/horizon/internal/expingest/database_backend_test.go
  services/horizon/internal/init.go
Labels: cla: yes

#2763 exp/ingest/ledgerbackend: Wrap metaPipe in bufio.Reader
  exp/ingest/ledgerbackend/stellar_core_runner_posix.go
  exp/ingest/ledgerbackend/stellar_core_runner_windows.go
  services/horizon/internal/expingest/fsm.go
Labels: cla: yes

#2762 support/keypairgen: add types and interface for keypair generation and mocking
  support/keypairgen/keypairgen.go
  support/keypairgen/keypairgen_test.go
  support/keypairgen/keypairgentest/slice.go
  support/keypairgen/keypairgentest/slice_test.go
Labels: cla: yes
