Repository stellar/go, pull requests merged in 2020-11, with the labels that each got.

#3183 xdr: Add a custom marshaller for claim predicate timestamp
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#3164 services/horizon: Update changelog with v1.11.0.
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3184 Merge horizon v1.11.0
  services/horizon/CHANGELOG.md
  xdr/json.go
  xdr/json_test.go
Labels: cla: yes

#3186 services/horizon: Bump Core in docker-compose image to version 15
  services/horizon/docker/Dockerfile
Labels: cla: yes

#3192 services/horizon/cmd: Fix db-url flag parsing in horizon db commands
  services/horizon/CHANGELOG.md
  services/horizon/cmd/db.go
  services/horizon/internal/flags.go
Labels: cla: yes

#3190 services/horizon: Publish a hash-tagged Horizon docker image for every master commit
  .circleci/config.yml
Labels: cla: yes

#3194 services/horizon: Fix typo in Circle's horizon hash-tag image publishing
  .circleci/config.yml
Labels: cla: yes

#3143 services/horizon: Move integration tests away from stellar/quickstart.
  .circleci/config.yml
  clients/stellarcore/client.go
  go.list
  go.mod
  go.sum
  services/horizon/docker/docker-compose.integration-tests.yml
  services/horizon/docker/docker-compose.standalone.yml
  services/horizon/docker/stellar-core-integration-tests.cfg
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/test/integration/integration.go
Labels: cla: yes

#3187 ingest/ledgerbackend: Decouple meta pipe buffering in CaptiveStellarCore backend
  ingest/ledgerbackend/buffered_meta_pipe_reader.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
  ingest/ledgerbackend/stellar_core_runner_posix.go
  ingest/ledgerbackend/stellar_core_runner_windows.go
  xdr/main.go
Labels: cla: yes

#3189 ingest: Render captive core logs as Horizon logs
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
  services/horizon/internal/ingest/main.go
Labels: cla: yes, fast-txmeta

#3207 txnbuild: correct installation instructions
  txnbuild/README.md
Labels: cla: yes

#3201 services/horizon: Avoid waiting for the first checkpoint in captive-core online mode
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3182 SEP10 v3.0: Add back homeDomain matching constraint for SEP-10 helpers
  exp/services/webauth/internal/serve/token.go
  txnbuild/transaction.go
  txnbuild/transaction_challenge_example_test.go
  txnbuild/transaction_test.go
Labels: cla: yes

#3199 txnbuild: Reinstate missing fee bump transaction functions
  txnbuild/CHANGELOG.md
  txnbuild/fee_bump_test.go
  txnbuild/transaction.go
Labels: cla: yes

#3216 services/horizon: Remove global ledger state
  services/horizon/internal/actions/account.go
  services/horizon/internal/actions/asset.go
  services/horizon/internal/actions/claimable_balance.go
  services/horizon/internal/actions/effects.go
  services/horizon/internal/actions/helpers.go
  services/horizon/internal/actions/helpers_test.go
  services/horizon/internal/actions/ledger.go
  services/horizon/internal/actions/offer.go
  services/horizon/internal/actions/operation.go
  services/horizon/internal/actions/operation_test.go
  services/horizon/internal/actions/root.go
  services/horizon/internal/actions/trade.go
  services/horizon/internal/actions/transaction.go
  services/horizon/internal/actions/transaction_test.go
  services/horizon/internal/app.go
  services/horizon/internal/db2/assets/asset_stat_test.go
  services/horizon/internal/db2/history/account_signers_test.go
  services/horizon/internal/db2/history/ledger_cache_test.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/db2/history/main_test.go
  services/horizon/internal/db2/history/operation_test.go
  services/horizon/internal/db2/history/trade_test.go
  services/horizon/internal/db2/history/transaction_test.go
  services/horizon/internal/httpx/handler.go
  services/horizon/internal/httpx/middleware.go
  services/horizon/internal/httpx/rate_limiter.go
  services/horizon/internal/httpx/router.go
  services/horizon/internal/httpx/server.go
  services/horizon/internal/httpx/stream_handler_test.go
  services/horizon/internal/ingest/database_backend_test.go
  services/horizon/internal/init.go
  services/horizon/internal/ledger/ledger_source.go
  services/horizon/internal/ledger/ledger_source_test.go
  services/horizon/internal/ledger/main.go
  services/horizon/internal/middleware_test.go
  services/horizon/internal/reap/main.go
  services/horizon/internal/reap/system.go
  services/horizon/internal/reap/system_test.go
  services/horizon/internal/resourceadapter/root.go
  services/horizon/internal/resourceadapter/root_test.go
  services/horizon/internal/test/integration/integration.go
  services/horizon/internal/test/t.go
  services/horizon/internal/txsub/results_test.go
Labels: cla: yes

#3220 services/horizon: Add captivecore command to Horizon container
  services/horizon/docker/Dockerfile
Labels: cla: yes

#3221 txnbuild: updated CHANGELOG.md for v5.0.0
  txnbuild/CHANGELOG.md
Labels: cla: yes

#3222 horizonclient: updated CHANGELOG.md for v5.0.0
  clients/horizonclient/CHANGELOG.md
Labels: cla: yes

#3215 Update Makefiles to label images with timestamps
  exp/services/recoverysigner/Makefile
  exp/services/webauth/Makefile
  services/friendbot/Makefile
  services/keystore/Makefile
  services/ticker/Makefile
Labels: cla: yes

#3203 ingest/ledgerbackend: Implement db backed ledger store for the captive core backend
  exp/services/captivecore/README.md
  exp/services/captivecore/main.go
  exp/tools/captive-core-start-tester/main.go
  ingest/doc_test.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/ledger_hash_store.go
  services/horizon/internal/db2/history/ledger_test.go
  services/horizon/internal/ingest/main.go
Labels: cla: yes

#3213 ingest/ledgerbackend: Fix flaky Captive Core tests
  ingest/ledgerbackend/buffered_meta_pipe_reader.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3225 ingest/ledgerbackend: Minor Core logging fixes
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3226 ingest/ledgerbackend: Fix CaptiveStellarCore.IsPrepared to include cached ledger
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
Labels: cla: yes

#3223 services/horizon/ingest: Call PrepareRange in verifyRange state
  services/horizon/internal/ingest/fsm.go
  services/horizon/internal/ingest/verify_range_state_test.go
Labels: cla: yes

#3231 ingest/ledgerbackend: Fix off-by-one in CaptiveStellarCore.runFromParams
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
Labels: cla: yes

#3232 exp/services/captivecore: Captive Core API fixes
  exp/services/captivecore/internal/api.go
  exp/services/captivecore/main.go
Labels: cla: yes

#3227 exp/services/recoverysigner: allow recoverysigner to sign transactions with operations containing a whitelisted source account
  exp/services/recoverysigner/README.md
  exp/services/recoverysigner/cmd/serve.go
  exp/services/recoverysigner/internal/serve/account_sign.go
  exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
  exp/services/recoverysigner/internal/serve/serve.go
Labels: cla: yes, recoverysigner

#3237 services/horizon: Trivial improvements to Stellar Core log parsing
  ingest/ledgerbackend/stellar_core_runner.go
Labels: cla: yes

#3245 services/horizon: Add CHANGELOG entry for Horizon 1.12.0
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3249 services/horizon/ingest: Batch remove offers
  services/horizon/internal/db2/history/mock_q_offers.go
  services/horizon/internal/db2/history/offers.go
  services/horizon/internal/db2/history/offers_test.go
  services/horizon/internal/db2/history/orderbook_test.go
  services/horizon/internal/ingest/processors/offers_processor.go
  services/horizon/internal/ingest/processors/offers_processor_test.go
Labels: cla: yes

#3250 Merge release-horizon-v1.12.0 into master
  exp/services/captivecore/internal/api.go
  exp/services/captivecore/main.go
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3253 services/horizon/docker: Fix STELLAR_CORE_BINARY_PATH in horizon docker image
  services/horizon/docker/Dockerfile
Labels: cla: yes

#3251 services/horizon/ingest: verifyState improvements
  services/horizon/internal/ingest/main_test.go
  services/horizon/internal/ingest/verify.go
Labels: cla: yes

#3255 ingest/ledgerbackend: Fix nil pointer dereference in captive core close
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
Labels: cla: yes

#3257 ingest/ledgerbackend: Add prev ledger hash check to CaptiveStellarCore
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  xdr/hash.go
  xdr/ledger_close_meta.go
Labels: cla: yes
