Repository stellar/go, pull requests merged in 2021-01, with the labels that each got.

#3296 services/keystore: improve health endpoint.
  services/keystore/api.go
Labels: cla: yes

#3307 services/horizon/internal/ingest: Move HistoryArchiveAdapter to internal horizon ingestion package
  ingest/adapters/mocks.go
  services/horizon/internal/ingest/build_state_test.go
  services/horizon/internal/ingest/db_integration_test.go
  services/horizon/internal/ingest/history_archive_adapter.go
  services/horizon/internal/ingest/history_archive_adapter_test.go
  services/horizon/internal/ingest/ingest_history_range_state_test.go
  services/horizon/internal/ingest/init_state_test.go
  services/horizon/internal/ingest/main.go
  services/horizon/internal/ingest/main_test.go
  services/horizon/internal/ingest/processor_runner.go
  services/horizon/internal/ingest/processor_runner_test.go
  services/horizon/internal/ingest/resume_state_test.go
  services/horizon/internal/ingest/sample_changes_test.go
  services/horizon/internal/ingest/stress_test.go
  services/horizon/internal/ingest/verify_range_state_test.go
  tools/archive-reader/archive_reader.go
Labels: cla: yes

#3302 horizon/docs: Minor aesthetic, phrasing, and grammatical improvements
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#3309 doc Use git clone instead of git checkout and suggest wrapping the po…
  services/horizon/internal/docs/developing.md
Labels: cla: yes

#3310 Merge release-horizon-v2.0.0-beta into master
  ingest/ledgerbackend/captive_core_backend.go
  ingest/ledgerbackend/captive_core_backend_test.go
  services/horizon/CHANGELOG.md
  services/horizon/internal/docs/HorizonWithCaptiveCore.png
  services/horizon/internal/docs/HorizonWithRemoteCaptiveCore.png
  services/horizon/internal/docs/HorizonWithoutCaptiveCore.png
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#3313 services/horizon: Restore old fixes to the Captive Core documentation
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#3314 services/friendbot: reduce friendbot minion creation batch to 50, allow for retries, add tests
  services/friendbot/friendbot.cfg
  services/friendbot/init_friendbot.go
  services/friendbot/init_friendbot_test.go
  services/friendbot/internal/account.go
  services/friendbot/internal/friendbot_test.go
  services/friendbot/internal/minion.go
  services/friendbot/internal/minion_test.go
  services/friendbot/main.go
Labels: cla: yes

#3318 ingest/io: Rename SingleLedgerStateReader
  exp/tools/dump-ledger-state/main.go
  ingest/doc_test.go
  ingest/io/change.go
  ingest/io/checkpoint_change_reader.go
  ingest/io/checkpoint_change_reader_test.go
  ingest/verify/main.go
  services/horizon/internal/ingest/history_archive_adapter.go
  services/horizon/internal/ingest/processor_runner.go
  tools/archive-reader/archive_reader.go
Labels: cla: yes

#3325 Update GET /metrics docs
  services/horizon/internal/docs/reference/endpoints/metrics.md
Labels: cla: yes

#3326 services/horizon: Fix fee stats calculations when fee bump transaction in the ledger
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/db2/history/operation.go
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/operation_fee_stats_1-horizon.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_2-horizon.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_3-horizon.sql
Labels: cla: yes

#3323 services/horizon: Rename all expingest references to ingest
  services/horizon/CHANGELOG.md
  services/horizon/cmd/ingest.go
  services/horizon/docker/verify-range/README.md
  services/horizon/docker/verify-range/start
  services/horizon/internal/action_offers_test.go
  services/horizon/internal/actions_account_test.go
  services/horizon/internal/actions_data_test.go
  services/horizon/internal/actions_effects_test.go
  services/horizon/internal/actions_payment_test.go
  services/horizon/internal/actions_transaction_test.go
  services/horizon/internal/app.go
  services/horizon/internal/db2/history/ingestion.go
  services/horizon/internal/db2/history/key_value.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/mock_q_signers.go
  services/horizon/internal/httpx/middleware.go
  services/horizon/internal/ingest/TESTING.md
  services/horizon/internal/ingest/build_state_test.go
  services/horizon/internal/ingest/db_integration_test.go
  services/horizon/internal/ingest/fsm.go
  services/horizon/internal/ingest/ingest_history_range_state_test.go
  services/horizon/internal/ingest/init_state_test.go
  services/horizon/internal/ingest/main.go
  services/horizon/internal/ingest/main_test.go
  services/horizon/internal/ingest/orderbook.go
  services/horizon/internal/ingest/orderbook_test.go
  services/horizon/internal/ingest/resume_state_test.go
  services/horizon/internal/ingest/stress_test.go
  services/horizon/internal/ingest/verify.go
  services/horizon/internal/ingest/verify_range_state_test.go
  services/horizon/internal/init.go
  services/horizon/internal/integration/protocol14_state_verifier_test.go
  services/horizon/internal/middleware_test.go
Labels: cla: yes

#3329 ingest: Conform processor implementations to their interfaces
  ingest/stats_change_processor.go
  ingest/stats_ledger_transaction_processor.go
Labels: cla: yes

#3328 ingest: Move the `Range` object to its own file.
  ingest/ledgerbackend/ledger_backend.go
  ingest/ledgerbackend/range.go
Labels: cla: yes

#3330 ingest: Remove errors subpackage from ingest
  ingest/doc_test.go
  ingest/errors.go
  ingest/errors/main.go
  ingest/ledger_entry_change_cache.go
  ingest/main.go
  ingest/verify/main.go
  ingest/verify/main_test.go
  services/horizon/internal/ingest/main.go
  services/horizon/internal/ingest/processors/account_data_processor.go
  services/horizon/internal/ingest/processors/accounts_processor.go
  services/horizon/internal/ingest/processors/asset_stats_processor.go
  services/horizon/internal/ingest/processors/claimable_balances_processor.go
  services/horizon/internal/ingest/processors/offers_processor.go
  services/horizon/internal/ingest/processors/offers_processor_test.go
  services/horizon/internal/ingest/processors/signer_processor_test.go
  services/horizon/internal/ingest/processors/signers_processor.go
  services/horizon/internal/ingest/processors/trust_lines_processor.go
  services/horizon/internal/ingest/processors/trust_lines_processor_test.go
  services/horizon/internal/ingest/verify.go
Labels: cla: yes

#3327 Horizon 1.13.1 CHANGELOG
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3333 services/horizon: Move ingest/verify to services/horizon/internal/verify
  services/horizon/internal/ingest/verify.go
  services/horizon/internal/ingest/verify/main.go
  services/horizon/internal/ingest/verify/main_test.go
Labels: cla: yes

#3335 ingest: Replace GenesisLedgerStateReader with GenesisChange function
  ingest/genesis.go
  ingest/genesis_ledger_state_reader.go
  ingest/genesis_ledger_state_reader_test.go
  ingest/genesis_test.go
  services/horizon/internal/ingest/processor_runner.go
  services/horizon/internal/ingest/processor_runner_test.go
Labels: cla: yes

#3336 Merge release-horizon-v1.13.1 into master
  services/horizon/CHANGELOG.md
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/db2/history/operation.go
  services/horizon/internal/test/scenarios/bindata.go
  services/horizon/internal/test/scenarios/operation_fee_stats_1-horizon.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_2-horizon.sql
  services/horizon/internal/test/scenarios/operation_fee_stats_3-horizon.sql
Labels: cla: yes

#3339 ingest: Remove HistoryArchiveBackend
  ingest/doc_test.go
  ingest/ledgerbackend/history_archive_backend.go
  ingest/ledgerbackend/history_archive_backend_test.go
Labels: cla: yes

#3337 Move ingest/ChangeProcessor interface to the horizon/internal/ingest
  exp/tools/dump-ledger-state/main.go
  ingest/mock_change_processor.go
  ingest/stats_change_processor.go
  services/horizon/internal/ingest/fsm.go
  services/horizon/internal/ingest/ingest_history_range_state_test.go
  services/horizon/internal/ingest/main_test.go
  services/horizon/internal/ingest/processor_runner.go
  services/horizon/internal/ingest/processor_runner_test.go
  services/horizon/internal/ingest/processors/change_processors.go
  services/horizon/internal/ingest/processors/change_processors_test.go
  services/horizon/internal/ingest/processors/mock_change_processor.go
  services/horizon/internal/ingest/processors/stats_ledger_transaction_processor.go
  services/horizon/internal/ingest/processors/stats_ledger_transaction_processor_test.go
  services/horizon/internal/ingest/resume_state_test.go
  services/horizon/internal/ingest/sample_changes_test.go
  services/horizon/internal/ingest/stress_test.go
  services/horizon/internal/ingest/verify_range_state_test.go
Labels: cla: yes

#3312 all: Use stdlib crypto/ed25519
  exp/crypto/derivation/main.go
  go.mod
  keypair/from_address.go
  keypair/full.go
Labels: cla: yes

#3343 services/horizon/internal/docs: Add documentation for running Captive Core on a private network
  services/horizon/internal/docs/captive_core.md
Labels: cla: yes

#3349 [CAP 35] Update XDR defintions and xdr package for CAP35
  services/horizon/internal/ingest/processors/effects_processor_test.go
  services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
  txnbuild/CHANGELOG.md
  txnbuild/allow_trust.go
  txnbuild/operation_test.go
  xdr/Stellar-ledger-entries.x
  xdr/Stellar-transaction.x
  xdr/asset.go
  xdr/asset_code.go
  xdr/asset_code_test.go
  xdr/asset_test.go
  xdr/go_string.go
  xdr/go_string_test.go
  xdr/xdr_generated.go
Labels: cla: yes

#3350 [CAP 35] Implement ingestion for Clawback operations
  protocols/horizon/operations/main.go
  services/horizon/internal/ingest/processors/operations_processor.go
  services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/resourceadapter/operations.go
Labels: cla: yes

#3351 [CAP 35] Add support for clawback account and trustline flags
  protocols/horizon/main.go
  services/horizon/internal/actions/asset_test.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/db2/history/trust_lines.go
  services/horizon/internal/ingest/processors/effects_processor.go
  services/horizon/internal/ingest/processors/operations_processor.go
  services/horizon/internal/resourceadapter/asset_stat.go
  services/horizon/internal/resourceadapter/asset_stat_test.go
  services/horizon/internal/resourceadapter/balance.go
  txnbuild/allow_trust.go
  txnbuild/operation_test.go
  txnbuild/set_options.go
  xdr/account_flags.go
  xdr/account_flags_test.go
  xdr/trust_line_flags.go
  xdr/trust_line_flags_test.go
Labels: cla: yes

#3332 services/horizon: Rename LedgerEntryChangeCache to ChangeCompactor
  ingest/ledger_entry_change_cache.go
  ingest/ledger_entry_change_cache_test.go
  services/horizon/internal/ingest/processors/account_data_processor.go
  services/horizon/internal/ingest/processors/accounts_processor.go
  services/horizon/internal/ingest/processors/asset_stats_processor.go
  services/horizon/internal/ingest/processors/claimable_balances_processor.go
  services/horizon/internal/ingest/processors/offers_processor.go
  services/horizon/internal/ingest/processors/offers_processor_test.go
  services/horizon/internal/ingest/processors/signers_processor.go
  services/horizon/internal/ingest/processors/trust_lines_processor.go
Labels: cla: yes

#3354 services/horizon: Fix fee stats with effective operation count when fee bump
  services/horizon/internal/actions_operation_fee_stats_test.go
  services/horizon/internal/db2/history/operation.go
Labels: cla: yes

#3353 services/horizon: Rewrite trade aggregation query to remove ARRAY usage
  services/horizon/internal/db2/history/trade_aggregation.go
  services/horizon/internal/resourceadapter/trade_aggregation.go
Labels: cla: yes

#3347 all: replace all circleci images with official images
  .circleci/config.yml
Labels: cla: yes

#3357 [CAP 35] Add support for SetOptions AuthRevocablRequired code
  services/horizon/internal/codes/main.go
  services/horizon/internal/codes/main_test.go
Labels: cla: yes

#3288 all: update scripts to test all code with go 1.16beta1
  .circleci/config.yml
  go.sum
Labels: cla: yes

#3360 services/horizon: Add Horizon 1.14.0 changelog
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3356 [CAP 35] Add support for new Claimable Balance clawback flag
  protocols/horizon/main.go
  services/horizon/internal/db2/history/claimable_balances.go
  services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
  services/horizon/internal/db2/schema/bindata.go
  services/horizon/internal/db2/schema/migrations/43_add_claimable_balances_flags.sql
  services/horizon/internal/ingest/processors/effects_processor.go
  services/horizon/internal/ingest/processors/effects_processor_test.go
  services/horizon/internal/ingest/verify.go
  services/horizon/internal/ingest/verify_range_state_test.go
  services/horizon/internal/ingest/verify_test.go
  services/horizon/internal/resourceadapter/claimable_balances.go
  services/horizon/internal/resourceadapter/claimable_balances_test.go
  xdr/account_flags.go
  xdr/account_flags_test.go
  xdr/claimable_balance_entry.go
  xdr/claimable_balance_entry_test.go
  xdr/claimable_balance_flags.go
  xdr/claimable_balance_flags_test.go
Labels: cla: yes

#3358 [CAP 35] Add effects for Clawback{ClaimableBalance} operations
  protocols/horizon/effects/main.go
  protocols/horizon/operations/main.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/ingest/processors/effects_processor.go
  services/horizon/internal/ingest/processors/effects_processor_test.go
  services/horizon/internal/ingest/processors/operations_processor.go
  services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/resourceadapter/effects.go
Labels: cla: yes

#3320 ingest: Add a tutorial for the ingestion libary.
  ingest/checkpoint_change_reader.go
  ingest/doc.go
  ingest/tutorial/example_claimables.go
  ingest/tutorial/example_common.go
  ingest/tutorial/example_hello.go
  ingest/tutorial/example_main.go
  ingest/tutorial/example_statistics.go
  ingest/tutorial/getting-started.md
  ingest/tutorial/stellar-core-stub.toml
Labels: cla: yes, docs, ingest

#3346 ingest: Introduce a new error for invalid checkpoint sequences
  historyarchive/range.go
  ingest/checkpoint_change_reader.go
  ingest/checkpoint_change_reader_test.go
Labels: cla: yes, ingest, small fix

#3363 [CAP 35] Populate account clawback flag
  services/horizon/internal/db2/history/accounts.go
  services/horizon/internal/resourceadapter/account_entry.go
  services/horizon/internal/resourceadapter/account_entry_test.go
Labels: cla: yes

#3367 horizon: Fix circle ci jobs which publish docker images
  .circleci/config.yml
Labels: cla: yes

#3362 ingest: Finish renaming LedgerEntryChangeCache to ChangeCompactor.
  ingest/change_compactor.go
  ingest/change_compactor_test.go
  services/horizon/internal/ingest/processors/account_data_processor.go
  services/horizon/internal/ingest/processors/accounts_processor.go
  services/horizon/internal/ingest/processors/asset_stats_processor.go
  services/horizon/internal/ingest/processors/claimable_balances_processor.go
  services/horizon/internal/ingest/processors/offers_processor.go
  services/horizon/internal/ingest/processors/signers_processor.go
  services/horizon/internal/ingest/processors/trust_lines_processor.go
Labels: cla: yes

#3304 services/horizon: Allow --stellar-core-binary-path to be prefilled from the PATH
  services/horizon/internal/flags.go
Labels: cla: yes, small fix

#3365 [CAP 35] Add operations stats for new clawback operations
  services/horizon/internal/ingest/processors/stats_ledger_transaction_processor.go
  services/horizon/internal/ingest/processors/stats_ledger_transaction_processor_test.go
Labels: cla: yes

#3364 [CAP 35] txnbuild: Add txnbuild support for the Clawback operation
  txnbuild/CHANGELOG.md
  txnbuild/allow_trust.go
  txnbuild/clawback.go
  txnbuild/clawback_test.go
Labels: cla: yes

#3370 all: use official docker images for publishing
  .circleci/config.yml
Labels: cla: yes

#3368 [CAP 35] Add Clawback happy path integration test
  .circleci/config.yml
  services/horizon/docker/Dockerfile
  services/horizon/docker/docker-compose.integration-tests.yml
  services/horizon/internal/ingest/main.go
  services/horizon/internal/ingest/processor_runner_test.go
  services/horizon/internal/integration/protocol14_test.go
  services/horizon/internal/integration/protocol_16_test.go
  services/horizon/internal/test/integration/integration.go
Labels: cla: yes

#3373 Merge Horizon v1.14.0 back into master
  services/horizon/CHANGELOG.md
Labels: cla: yes

#3308 strkey: Fix panic on invalid length decoded string
  strkey/decode_test.go
  strkey/main.go
Labels: cla: yes

#3374 [CAP 35] Update XDR definitions with the latest CAP updates
  xdr/Stellar-ledger-entries.x
  xdr/Stellar-transaction.x
  xdr/xdr_generated.go
Labels: cla: yes

#3376 [CAP 35] Add support for new result codes in CAP35
  services/horizon/internal/codes/main.go
  services/horizon/internal/codes/main_test.go
Labels: cla: yes

#3372 clients/horizonclient fix request timeout
  clients/horizonclient/client.go
Labels: cla: yes, horizonclient

#3378 [CAP35] Add support for SetTrustLineFlags operation
  protocols/horizon/effects/main.go
  protocols/horizon/operations/main.go
  services/horizon/internal/db2/history/main.go
  services/horizon/internal/ingest/processors/effects_processor.go
  services/horizon/internal/ingest/processors/effects_processor_test.go
  services/horizon/internal/ingest/processors/operations_processor.go
  services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
  services/horizon/internal/resourceadapter/effects.go
  services/horizon/internal/resourceadapter/operations.go
  txnbuild/allow_trust.go
  txnbuild/operation.go
  txnbuild/set_trust_line_flags.go
  txnbuild/set_trustline_flags_test.go
  xdr/xdr_generated.go
Labels: cla: yes
