Repository stellar/go, pull requests merged in 2021-07, with the labels that each got.

#3746 ingest: Properly parse and emit debug-level tags from Captive Core.
  ingest/CHANGELOG.md
  ingest/ledgerbackend/stellar_core_runner.go
Labels: bug

#3761 txnbuild: Fix minor typo in `SetTrustLineFlags.BuildXDR()` docstring.
  txnbuild/set_trust_line_flags.go
Labels: docs

#3779 txnbuild: remove error from return values of AddSignatureDecorated
  txnbuild/CHANGELOG.md
  txnbuild/transaction.go
  txnbuild/transaction_test.go
Labels: txnbuild
